#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Areas\manage\Views\User\Add.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\manage\Views\User\Add.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/User/Add.cshtml")]
    public partial class _Areas_manage_Views_User_Add_cshtml : System.Web.Mvc.WebViewPage<UserViewModel>
    {
        public _Areas_manage_Views_User_Add_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\manage\Views\User\Add.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 10 "..\..\Areas\manage\Views\User\Add.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Areas\manage\Views\User\Add.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Areas\manage\Views\User\Add.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Areas\manage\Views\User\Add.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .form-horizontal .form-label {\r\n        text-align: right;\r\n    }\r\n</style" +
">\r\n<article");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\manage\Views\User\Add.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\manage\Views\User\Add.cshtml"
     using (Ajax.BeginForm("Add", "User", new { }, new AjaxOptions() { HttpMethod = "Post", OnSuccess = "formSuccess(data)", OnBegin = "disSubmit('sub_btn')", OnComplete = "enSubmit('sub_btn')" }, new { id = "", @class = "form form-horizontal" }))
    {
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\manage\Views\User\Add.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\manage\Views\User\Add.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\manage\Views\User\Add.cshtml"
   Write(Html.HiddenFor(m => m.Id,new {@Value=0 }));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\manage\Views\User\Add.cshtml"
                                                  

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>用户名：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 27 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.TextBoxFor(m => m.UserName, new { placeholder = "请输入用户名", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.UserName, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>姓名：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 34 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.TextBoxFor(m => m.RealName, new { placeholder = "请输入姓名", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.RealName, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>手机号：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.TextBoxFor(m => m.Phone, new { placeholder = "请输入手机号", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.Phone, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">邮箱：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.TextBoxFor(m => m.Email, new { placeholder = "请输入邮箱", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 49 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.Email, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>密码：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.PasswordFor(m => m.Password, new { placeholder = "6-20位字符，可由英文、数字和特殊符号组成", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Areas\manage\Views\User\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.Password, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">状态：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"select select-box\"");

WriteLiteral(" name=\"State\"");

WriteLiteral(">\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2983), Tuple.Create("\"", 3017)
            
            #line 64 "..\..\Areas\manage\Views\User\Add.cshtml"
, Tuple.Create(Tuple.Create("", 2991), Tuple.Create<System.Object, System.Int32>((int)PublishState.Upper
            
            #line default
            #line hidden
, 2991), false)
);

WriteLiteral(">上架</option>\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3059), Tuple.Create("\"", 3093)
            
            #line 65 "..\..\Areas\manage\Views\User\Add.cshtml"
, Tuple.Create(Tuple.Create("", 3067), Tuple.Create<System.Object, System.Int32>((int)PublishState.Lower
            
            #line default
            #line hidden
, 3067), false)
);

WriteLiteral(">下架</option>\r\n                </select>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(" class=\"col-xs-6  col-xs-offset-3 col-sm-offset-2 mt-10\"");

WriteLiteral(">\r\n\r\n                <button");

WriteLiteral(" class=\"btn btn-primary radius\"");

WriteLiteral(" id=\"sub_btn\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">保存</button>\r\n                <input");

WriteLiteral(" name=\"\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"layer_close();\"");

WriteLiteral(" class=\"btn btn-default radius \"");

WriteLiteral(" value=\"取消\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n");

            
            #line 76 "..\..\Areas\manage\Views\User\Add.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</article>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function formSuccess(result) {
        if (result != null) {
            if (result.isSuccess) {
                var index = parent.layer.getFrameIndex(window.name);
                layer.alert('保存成功！', {
                    icon: 6,
                    closeBtn: 0,
                    yes: function () {
                        if (parent[1] != null) {
                            parent[pageIndex()].table1.ajax.reload();
                        } else {
                            parent.table1.ajax.reload();
                        }
                        parent.layer.close(index);
                    }
                });
            } else
                layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
        } else
            layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
    }
</script>");

        }
    }
}
#pragma warning restore 1591
