#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\manage\Views\User\List.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\manage\Views\User\List.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/User/List.cshtml")]
    public partial class _Areas_manage_Views_User_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_manage_Views_User_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<nav");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 系统设置 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 账户管理 <a");

WriteLiteral(" class=\"btn btn-primary radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cl pd-10 bg-1 bk-gray mt-10 search-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">筛选：</span>\r\n        <select");

WriteLiteral(" name=\"sel_orderstate\"");

WriteLiteral(" id=\"sel_filType\"");

WriteLiteral(" class=\"select select-box sm inline\"");

WriteLiteral(">\r\n            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择筛选条件</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 671), Tuple.Create("\"", 704)
            
            #line 10 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 679), Tuple.Create<System.Object, System.Int32>((int)SearchType.Number
            
            #line default
            #line hidden
, 679), false)
);

WriteLiteral(">手机号</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 739), Tuple.Create("\"", 770)
            
            #line 11 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 747), Tuple.Create<System.Object, System.Int32>((int)SearchType.Name
            
            #line default
            #line hidden
, 747), false)
);

WriteLiteral(">姓名</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 804), Tuple.Create("\"", 836)
            
            #line 12 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 812), Tuple.Create<System.Object, System.Int32>((int)SearchType.State
            
            #line default
            #line hidden
, 812), false)
);

WriteLiteral(">状态</option>\r\n        </select>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"sel_filVal\"");

WriteLiteral(" placeholder=\"请输入筛选关键字\"");

WriteLiteral(" class=\"input-text lg inline hidden\"");

WriteLiteral(" />\r\n        <select");

WriteLiteral(" name=\"sel_orderstate\"");

WriteLiteral(" id=\"sel_state\"");

WriteLiteral(" class=\"select select-box sm inline hidden\"");

WriteLiteral(" style=\"min-width:150px\"");

WriteLiteral(">\r\n            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择账户状态</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1164), Tuple.Create("\"", 1198)
            
            #line 17 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 1172), Tuple.Create<System.Object, System.Int32>((int)PublishState.Upper
            
            #line default
            #line hidden
, 1172), false)
);

WriteLiteral(">已上架</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1233), Tuple.Create("\"", 1267)
            
            #line 18 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 1241), Tuple.Create<System.Object, System.Int32>((int)PublishState.Lower
            
            #line default
            #line hidden
, 1241), false)
);

WriteLiteral(">已下架</option>\r\n        </select>\r\n        <button");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteLiteral(" class=\"btn btn-success ml-20\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe665;</i> 查询</button>\r\n");

            
            #line 21 "..\..\Areas\manage\Views\User\List.cshtml"
        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\manage\Views\User\List.cshtml"
         if (ViewBag.IsSupAdmin)
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1526), Tuple.Create("\"", 1573)
, Tuple.Create(Tuple.Create("", 1536), Tuple.Create("user_add(\'新建账户\',\'", 1536), true)
            
            #line 23 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 1553), Tuple.Create<System.Object, System.Int32>(Url.Action("Add")
            
            #line default
            #line hidden
, 1553), false)
, Tuple.Create(Tuple.Create("", 1571), Tuple.Create("\')", 1571), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">新建账户</button>\r\n");

            
            #line 24 "..\..\Areas\manage\Views\User\List.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"is_admin\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1657), Tuple.Create("\"", 1684)
            
            #line 25 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 1665), Tuple.Create<System.Object, System.Int32>(ViewBag.IsSupAdmin
            
            #line default
            #line hidden
, 1665), false)
);

WriteLiteral(" />\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"user_id\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1731), Tuple.Create("\"", 1754)
            
            #line 26 "..\..\Areas\manage\Views\User\List.cshtml"
, Tuple.Create(Tuple.Create("", 1739), Tuple.Create<System.Object, System.Int32>(ViewBag.UserId
            
            #line default
            #line hidden
, 1739), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"mt-10\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"tbTable\"");

WriteLiteral(" class=\"table table-border table-bordered table-bg table-sort\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr");

WriteLiteral(" class=\"text-c\"");

WriteLiteral(">\r\n                    <th");

WriteLiteral(" width=\"8%\"");

WriteLiteral(">序号</th>\r\n                    <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">用户名</th>\r\n                    <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">姓名</th>\r\n                    <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">手机号</th>\r\n                    <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">邮箱</th>\r\n                    <th");

WriteLiteral(" width=\"8%\"");

WriteLiteral(">状态</th>\r\n                    <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">创建时间</th>\r\n                    <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">操作</th>\r\n                </tr>\r\n            </thead>\r\n        </table>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var table1 = null;
        $(function () {
            table1 = initializeTable();
            $(""#search"").click(function () {
                table1.ajax.reload();
            });

            //输入名称回车查询
            $(""#sel_filVal"").keypress(function (e) {
                if (e.which == 13) {
                    table1.ajax.reload();
                    $(""#search"").focus();
                }
            });

            $(""#sel_filType"").change(function () {
                if ($(this).val() == """") {
                    $(""#sel_state"").addClass(""hidden"");
                    $(""#sel_filVal"").addClass(""hidden"");
                }
                else if ($(this).val() == '");

            
            #line 68 "..\..\Areas\manage\Views\User\List.cshtml"
                                       Write((int)SearchType.State);

            
            #line default
            #line hidden
WriteLiteral(@"') {
                    $(""#sel_state"").removeClass(""hidden"");
                    $(""#sel_filVal"").addClass(""hidden"");
                } else {
                    $(""#sel_filVal"").removeClass(""hidden"");
                    $(""#sel_state"").addClass(""hidden"");
                }

                $(""#sel_filVal,#sel_state"").val("""");
            })
        });

        /*编辑*/
        function user_deit(title, url, id) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['750px', '480px'],
                content: url + ""?id="" + id
            });
        }

        /*添加*/
        function user_add(title, url) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['750px', '520px'],
                content: url
            });
        }

        function initPwd(id) {
            layer.confirm('初始化密码为手机号后6位，您确定要初始化吗？', function (e) {
                $.ajax({
                    url: """);

            
            #line 103 "..\..\Areas\manage\Views\User\List.cshtml"
                     Write(Url.Action("InitPwd"));

            
            #line default
            #line hidden
WriteLiteral(@""",
                    type: ""post"",
                    data: { uid: id },
                    success: function (data) {
                        if (data == ""ok"") {
                            layer.alert('初始化成功！', { icon: 6 });
                        } else if (data == ""error"") {
                            layer.alert('操作失败！', { icon: 5 });
                        }
                        else {
                            layer.alert(data, { icon: 7 });
                        }
                    },
                    error: function (data) { layer.alert('操作失败！', { icon: 5 }); }
                })
            })
        }

        function getFilterVal() {
            if ($(""#sel_filType"").val() == '");

            
            #line 122 "..\..\Areas\manage\Views\User\List.cshtml"
                                        Write((int)SearchType.State);

            
            #line default
            #line hidden
WriteLiteral(@"') {
                return $(""#sel_state"").val();
            } else {
                return $(""#sel_filVal"").val();
            }

        }

        function initializeTable() {
            var dataTable = $('#tbTable').DataTable({
                ""serverSide"": true,
                ""ajax"": {
                    ""url"": """);

            
            #line 134 "..\..\Areas\manage\Views\User\List.cshtml"
                       Write(Url.Action("GetJsonData"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    \"type\": \"post\",\r\n                    \"data\": function (da" +
"ta) {\r\n                        data.pageIndex = (data.start / data.length) + 1;\r" +
"\n                        data.filterKey = $(\"#sel_filType\").val();\r\n            " +
"            data.filterVal = getFilterVal();\r\n                    }\r\n           " +
"     },\r\n                \"columns\": [\r\n                      { \"defaultContent\":" +
" \"\" },\r\n                      { \"mDataProp\": \"UserName\" },\r\n                    " +
"{ \"mDataProp\": \"RealName\" },\r\n                      { \"mDataProp\": \"Phone\" },\r\n " +
"                     { \"mDataProp\": \"Email\" },\r\n                       { \"mDataP" +
"rop\": \"State\" },\r\n                       { \"mDataProp\": \"CreateTime\" },\r\n       " +
"               { \"defaultContent\": \"\" }\r\n\r\n                ],\r\n                \"" +
"columnDefs\": [\r\n                 {\r\n                     \"targets\": [5],\r\n      " +
"               \"data\": \"State\",\r\n                     \"render\": function (data, " +
"type, full) {\r\n                         var result = data;\r\n                    " +
"     if (data > 0) {\r\n                             result = \"<span class=\\\"label" +
" label-success radius\\\">已上架</span>\";\r\n                         } else {\r\n       " +
"                      result = \"<span class=\\\"label label-danger radius\\\">已下架</s" +
"pan>\";\r\n                         }\r\n\r\n                         return result;\r\n " +
"                    }\r\n                 },\r\n                {\r\n                 " +
"   \"targets\": [-1],\r\n                    \"data\": \"Id\",\r\n                    \"ren" +
"der\": function (data, type, full) {\r\n                        var isAdmin = $(\"#i" +
"s_admin\").val();\r\n                        var tmpString = \"<a  onClick=\\\"user_de" +
"it(\'修改账户\',\'");

            
            #line 173 "..\..\Areas\manage\Views\User\List.cshtml"
                                                                    Write(Url.Action("Edit"));

            
            #line default
            #line hidden
WriteLiteral(@"',"" + data + "")\"" href=\""javascript:;\"" title=\""编辑\"">编辑</a>"";
                        if (isAdmin) {
                            if ($(""#user_id"").val() == data) {
                                tmpString += ""<a href=\""javascript:;\"" onClick=\""initPwd("" + data + "")\""  title=\""初始化密码\"">初始化密码</a>"";
                            } else {
                                if (full.State == 0)
                                    tmpString += ""<a href=\""javascript:;\"" onClick=\""obj_publish('");

            
            #line 179 "..\..\Areas\manage\Views\User\List.cshtml"
                                                                                             Write(Url.Action("Publish"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\"  title=\\\"上架\\\">上架</a>\";\r\n                                else\r\n " +
"                                   tmpString += \"<a href=\\\"javascript:;\\\" onClic" +
"k=\\\"obj_shelves(\'");

            
            #line 181 "..\..\Areas\manage\Views\User\List.cshtml"
                                                                                             Write(Url.Action("Shelves"));

            
            #line default
            #line hidden
WriteLiteral(@"',"" + data + "")\""  title=\""下架\"">下架</a>"";
                                tmpString += ""<a href=\""javascript:;\"" onClick=\""initPwd("" + data + "")\""  title=\""初始化密码\"">初始化密码</a>"";
                                tmpString += ""<a href=\""javascript:;\"" onClick=\""obj_del('账户','");

            
            #line 183 "..\..\Areas\manage\Views\User\List.cshtml"
                                                                                          Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\"  title=\\\"删除\\\">删除</a>\";\r\n                            }\r\n        " +
"                } else {\r\n                            if ($(\"#user_id\").val() !=" +
" data) {\r\n                                tmpString = \"不可操作\";\r\n                 " +
"           }\r\n                        }\r\n\r\n                        return tmpStr" +
"ing;\r\n                    }\r\n                }\r\n                ],\r\n            " +
"    \"fnDrawCallback\": function () {\r\n                    var api = this.api();\r\n" +
"                    var startIndex = api.context[0]._iDisplayStart;\r\n           " +
"         api.column(0).nodes().each(function (cell, i) {\r\n                      " +
"  cell.innerHTML = startIndex + i + 1;\r\n                    });\r\n               " +
" },\r\n                \"rowCallback\": function (row, data, displayIndex) {\r\n      " +
"              $(row).attr(\"class\", \"text-c\");\r\n                    $(row).childr" +
"en(\'td\').eq(5).attr(\"class\", \"td-status\");\r\n                    $(row).children(" +
"\'td\').eq(7).attr(\"class\", \"td-manage\");\r\n                },\r\n                \"in" +
"itComplete\": function (settings, json) {\r\n\r\n                },\r\n                " +
"language: {\r\n                    lengthMenu: \'\',\r\n                    loadingRec" +
"ords: \'数据加载中...\',\r\n                    paginate: {\r\n                        prev" +
"ious: \"上一页\",\r\n                        next: \"下一页\",\r\n                        firs" +
"t: \"\",\r\n                        last: \"\"\r\n                    },\r\n              " +
"      zeroRecords: \"暂无数据\",\r\n\r\n                    info: \"<span class=\'pagesStyle" +
"\'>总共<span class=\'recordsStyle\'> _TOTAL_ 条,计 _PAGES_ </span>页，当前显示 _START_ -- _EN" +
"D_ 条记录 </span>\",\r\n                    infoEmpty: \"0条记录\",\r\n                    in" +
"foFiltered: \"\"\r\n                },\r\n                \"searching\": false,\r\n       " +
"         \"ordering\": false,\r\n                \"autoWidth\": false,\r\n              " +
"  \"iDisplayLength\": 10,\r\n                \"processing\": true,\r\n                //" +
"destroy: true, //Cannot reinitialise DataTable,解决重新加载表格内容问题\r\n\r\n            });\r\n" +
"            return dataTable;\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
