#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Shared\_Layout.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    using HST.Art.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Layout.cshtml"
  
    string action = Request.RequestContext.RouteData.GetRequiredString("Action");
    string queryName = string.IsNullOrEmpty(Request.QueryString["qtype"]) ? "" : Request.QueryString["qtype"];

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"renderer\"");

WriteLiteral(" content=\"webkit|ie-comp|ie-stand\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0," +
"user-scalable=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-siteapp\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(" content=\"教育,教育委员会,建设,专业,职业,山东省,职业教育,艺术,艺术培训,艺术指导委员会\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"山东省艺术职业教育专业建设指导委员会\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteLiteral(" rel=\"Shortcut Icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" />\r\n    <!--[if lt IE 9]>\r\n    <script type=\"text/javascript\" src=\"/Content/lib/" +
"html5shiv.js\"></script>\r\n    <script type=\"text/javascript\" src=\"/Content/lib/re" +
"spond.min.js\"></script>\r\n    <![endif]-->\r\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/webclient"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
     if (action.Equals("index", StringComparison.InvariantCultureIgnoreCase))
    {
        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\_Layout.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1230), Tuple.Create("\"", 1265)
, Tuple.Create(Tuple.Create("", 1237), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/swiper.min.css")
, 1237), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1299), Tuple.Create("\"", 1340)
, Tuple.Create(Tuple.Create("", 1306), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/owl.carousel.min.css")
, 1306), false)
);

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/webclient"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body ");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
  Write(action.Equals("index", StringComparison.InvariantCultureIgnoreCase) ? "style=background:#f2f2f2" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n    <header>\r\n        <div");

WriteLiteral(" class=\"top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"cont top_div\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("Header", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div><!--/top-->\r\n    </header>\r\n    <nav>\r\n      " +
"  <div");

WriteLiteral(" class=\"nav-logo\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1811), Tuple.Create("\"", 1846)
            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1818), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 1818), false)
);

WriteLiteral("><img");

WriteLiteral(" src=\"/Content/image/logo.jpg\"");

WriteLiteral(" alt=\"\"");

WriteLiteral("></a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"nav-menu\"");

WriteLiteral(">\r\n            <span></span>\r\n            <span></span>\r\n            <span></span" +
">\r\n        </div>\r\n       \r\n        <ul");

WriteLiteral(" class=\"nav-list\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2099), Tuple.Create("\"", 2134)
            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2106), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 2106), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 2135), Tuple.Create("\"", 2288)
            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2143), Tuple.Create<System.Object, System.Int32>(action.Equals("index",StringComparison.InvariantCultureIgnoreCase)||action.Equals("certificate",StringComparison.InvariantCulture)?"active":""
            
            #line default
            #line hidden
, 2143), false)
);

WriteLiteral(">首页</a></li>\r\n            <li>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2339), Tuple.Create("\"", 2373)
            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2346), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home")
            
            #line default
            #line hidden
, 2346), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 2374), Tuple.Create("\"", 2463)
            
            #line 55 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2382), Tuple.Create<System.Object, System.Int32>(action.Equals("about",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2382), false)
);

WriteLiteral(">协会概况</a>\r\n                <ul");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2533), Tuple.Create("\"", 2628)
            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2541), Tuple.Create<System.Object, System.Int32>(queryName.Equals("Synopsis",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2541), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2632), Tuple.Create("\"", 2699)
            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 2639), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { qtype = QSType.synopsis })
            
            #line default
            #line hidden
, 2639), false)
);

WriteLiteral(">协会简介</a></li>\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2739), Tuple.Create("\"", 2831)
            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2747), Tuple.Create<System.Object, System.Int32>(queryName.Equals("Frame",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 2747), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2835), Tuple.Create("\"", 2899)
            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
                                              , Tuple.Create(Tuple.Create("", 2842), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { qtype = QSType.frame })
            
            #line default
            #line hidden
, 2842), false)
);

WriteLiteral(">组织架构</a></li>\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2939), Tuple.Create("\"", 3172)
            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2947), Tuple.Create<System.Object, System.Int32>(action.Equals("about",StringComparison.InvariantCultureIgnoreCase)&&(queryName.Equals("List",StringComparison.InvariantCultureIgnoreCase)||queryName.Equals("Detail",StringComparison.InvariantCultureIgnoreCase))?"active":""
            
            #line default
            #line hidden
, 2947), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3176), Tuple.Create("\"", 3239)
            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                           , Tuple.Create(Tuple.Create("", 3183), Tuple.Create<System.Object, System.Int32>(Url.Action("About","Home", new { qtype = QSType.list })
            
            #line default
            #line hidden
, 3183), false)
);

WriteLiteral(">协会会员</a></li>\r\n                </ul>\r\n            </li>\r\n            <li>\r\n     " +
"           <a");

WriteAttribute("class", Tuple.Create(" class=\"", 3334), Tuple.Create("\"", 3426)
            
            #line 63 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3342), Tuple.Create<System.Object, System.Int32>(action.Equals("industry",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 3342), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 3427), Tuple.Create("\"", 3457)
            
            #line 63 "..\..\Views\Shared\_Layout.cshtml"
                                      , Tuple.Create(Tuple.Create("", 3434), Tuple.Create<System.Object, System.Int32>(Url.Action("industry")
            
            #line default
            #line hidden
, 3434), false)
);

WriteLiteral(">行业资讯</a>\r\n");

WriteLiteral("                ");

            
            #line 64 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Industry }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 3621), Tuple.Create("\"", 3716)
            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3629), Tuple.Create<System.Object, System.Int32>(action.Equals("association",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 3629), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 3717), Tuple.Create("\"", 3750)
            
            #line 67 "..\..\Views\Shared\_Layout.cshtml"
                                         , Tuple.Create(Tuple.Create("", 3724), Tuple.Create<System.Object, System.Int32>(Url.Action("association")
            
            #line default
            #line hidden
, 3724), false)
);

WriteLiteral(">协会活动</a>\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Association }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 3917), Tuple.Create("\"", 4007)
            
            #line 71 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3925), Tuple.Create<System.Object, System.Int32>(action.Equals("social",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 3925), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 4008), Tuple.Create("\"", 4036)
            
            #line 71 "..\..\Views\Shared\_Layout.cshtml"
                                    , Tuple.Create(Tuple.Create("", 4015), Tuple.Create<System.Object, System.Int32>(Url.Action("social")
            
            #line default
            #line hidden
, 4015), false)
);

WriteLiteral(">社会公益</a>\r\n");

WriteLiteral("                ");

            
            #line 72 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Social }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 4198), Tuple.Create("\"", 4293)
            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4206), Tuple.Create<System.Object, System.Int32>(action.Equals("examination",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 4206), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 4294), Tuple.Create("\"", 4327)
            
            #line 75 "..\..\Views\Shared\_Layout.cshtml"
                                         , Tuple.Create(Tuple.Create("", 4301), Tuple.Create<System.Object, System.Int32>(Url.Action("examination")
            
            #line default
            #line hidden
, 4301), false)
);

WriteLiteral(">考级中心</a>\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Examination }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 4494), Tuple.Create("\"", 4586)
            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4502), Tuple.Create<System.Object, System.Int32>(action.Equals("download",StringComparison.InvariantCultureIgnoreCase)?"active":""
            
            #line default
            #line hidden
, 4502), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 4587), Tuple.Create("\"", 4617)
            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
                                      , Tuple.Create(Tuple.Create("", 4594), Tuple.Create<System.Object, System.Int32>(Url.Action("download")
            
            #line default
            #line hidden
, 4594), false)
);

WriteLiteral(">下载专区</a>\r\n");

WriteLiteral("                ");

            
            #line 80 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Action("SecondMenu", "Home", new { sectionType = CategoryType.Download }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ul>\r\n    </nav>\r\n    <div");

WriteLiteral(" class=\"nav-zhan\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"content-wrap\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 86 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"foot\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"foot_cont\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 90 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Action("Footer", "Home"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <footer>京ICP备20011563号-1</footer>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            var topMain = $(\"header\")" +
".height();\r\n            //var topNav = $(\"nav\").outerHeight();\r\n            //va" +
"r topHeight = isMobile() ? topNav : topMain;\r\n            var nav = $(\"nav\");\r\n " +
"           if (!isMobile()) {\r\n                $(window).scroll(function () {\r\n " +
"                   if ($(window).scrollTop() > topMain) {\r\n                     " +
"   nav.addClass(\"nav_scroll\");\r\n                    } else {\r\n                  " +
"      nav.removeClass(\"nav_scroll\");\r\n                    }\r\n                });" +
"\r\n            }\r\n        })\r\n\r\n        $(document).click(function () {\r\n        " +
"    $(\'.nav-list\').removeClass(\'open\')\r\n        })\r\n        $(\'.nav-menu,.nav-li" +
"st\').click(function (e) { e.stopPropagation() })\r\n        $(\'nav\').find(\'.nav-me" +
"nu\').click(function (e) {\r\n            $(\'.nav-list\').toggleClass(\'open\')\r\n     " +
"   })\r\n\r\n        function isMobile() {\r\n            var userAgentInfo = navigato" +
"r.userAgent;\r\n            var mobileAgents = [\"Android\", \"iPhone\", \"SymbianOS\", " +
"\"Windows Phone\", \"iPad\", \"iPod\"];\r\n            var mobile_flag = false;\r\n       " +
"     //根据userAgent判断是否是手机\r\n            for (var v = 0; v < mobileAgents.length; " +
"v++) {\r\n                if (userAgentInfo.indexOf(mobileAgents[v]) > 0) {\r\n     " +
"               mobile_flag = true;\r\n                    break;\r\n                " +
"}\r\n            }\r\n            var screen_width = window.screen.width;\r\n         " +
"   // var screen_height = window.screen.height;\r\n            //根据屏幕分辨率判断是否是手机\r\n " +
"           if (screen_width < 996) {\r\n                mobile_flag = true;\r\n     " +
"       }\r\n            return mobile_flag;\r\n        }\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 139 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
