#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HST.Art.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/Home/welcome.cshtml")]
    public partial class _Areas_manage_Views_Home_welcome_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_manage_Views_Home_welcome_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\manage\Views\Home\welcome.cshtml"
  
    ViewBag.Title = "我的桌面";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\manage\Views\Home\welcome.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\manage\Views\Home\welcome.cshtml"
Write(Styles.Render("~/patternfly"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\manage\Views\Home\welcome.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Areas\manage\Views\Home\welcome.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Areas\manage\Views\Home\welcome.cshtml"
Write(Scripts.Render("~/bundles/D-C3"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    .card-pf {\r\n        box-shadow: 1px 1px 10px 0px rgba(3,3,3,.175" +
");\r\n    }\r\n</style>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"card-pf card-pf-utilization\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card-pf-heading\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"card-pf-heading-details\"");

WriteLiteral(">最近 30 天</p>\r\n                <h2");

WriteLiteral(" class=\"card-pf-title\"");

WriteLiteral(">\r\n                    系统分析\r\n                </h2>\r\n            </div>\r\n         " +
"   <div");

WriteLiteral(" class=\"card-pf-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"card-pf-subtitle\"");

WriteLiteral(">资料包统计</h3>\r\n                        <p");

WriteLiteral(" class=\"card-pf-utilization-details\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-count\"");

WriteLiteral(" id=\"package_total\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-description\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-line-1\"");

WriteLiteral(">总数</span>\r\n                            </span>\r\n                            <spa" +
"n");

WriteLiteral(" style=\"margin-left:40px\"");

WriteLiteral(" class=\"card-pf-utilization-card-details-count\"");

WriteLiteral(" id=\"package_enable\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-description\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-line-1\"");

WriteLiteral(">启用数</span>\r\n                            </span>\r\n                            <sp" +
"an");

WriteLiteral(" style=\"margin-left:40px\"");

WriteLiteral(" class=\"card-pf-utilization-card-details-count\"");

WriteLiteral(" id=\"package_disable\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-description\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-line-1\"");

WriteLiteral(">禁用数</span>\r\n                            </span>\r\n                        </p>\r\n\r" +
"\n                        <div");

WriteLiteral(" id=\"chart-pf-donut-2\"");

WriteLiteral("></div>\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"card-pf-subtitle\"");

WriteLiteral(">资料统计</h3>\r\n                        <p");

WriteLiteral(" class=\"card-pf-utilization-details\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-count\"");

WriteLiteral(" id=\"res_total\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-description\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-line-1\"");

WriteLiteral(">总数</span>\r\n                            </span>\r\n                            <spa" +
"n");

WriteLiteral(" style=\"margin-left:40px\"");

WriteLiteral(" class=\"card-pf-utilization-card-details-count\"");

WriteLiteral(" id=\"res_enable\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-description\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-line-1\"");

WriteLiteral(">启用数</span>\r\n                            </span>\r\n                            <sp" +
"an");

WriteLiteral(" style=\"margin-left:40px\"");

WriteLiteral(" class=\"card-pf-utilization-card-details-count\"");

WriteLiteral(" id=\"res_disable\"");

WriteLiteral("></span>\r\n                            <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-description\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"card-pf-utilization-card-details-line-1\"");

WriteLiteral(">禁用数</span>\r\n                            </span>\r\n                        </p>\r\n\r" +
"\n                        <div");

WriteLiteral(" id=\"chart-pf-donut-3\"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"        </div>\r\n    </div>\r\n</div>\r\n<script>\r\n    $(function () {\r\n\r\n\r\n    });\r\n" +
"    ");

WriteLiteral("\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
