#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using cncbk_resource;
    
    #line 5 "..\..\Views\ResPermission\Index.cshtml"
    using cncbk_resource.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResPermission/Index.cshtml")]
    public partial class _Views_ResPermission_Index_cshtml : System.Web.Mvc.WebViewPage<FilterViewModel>
    {
        public _Views_ResPermission_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!--[if lt IE 9]>\r\n<script type=\"text/javascript\" src=\"lib/html5shiv.js\"></script" +
">\r\n<script type=\"text/javascript\" src=\"lib/respond.min.js\"></script>\r\n<![endif]-" +
"->\r\n");

            
            #line 6 "..\..\Views\ResPermission\Index.cshtml"
Write(Styles.Render("~/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\ResPermission\Index.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral(@"    <style>
    .table-bordered>thead>tr>td, .table-bordered>thead>tr>th{border-bottom-width:0px;border-left-width:0px}
    .table-bordered>tbody>tr>td{border-left-width:0px;border-bottom-width:0px;}
    .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th{vertical-align:middle;line-height:20px}
    .table-bordered{border:1px solid #ddd;border-bottom: 1px solid #ddd !important;border-right-width: 0px;}
     </style>
<!--[if IE 6]>
<script type=""text/javascript"" src=""lib/DD_belatedPNG_0.0.8a-min.js"" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<nav");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 用户学习资料 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span> 用户权限 <a");

WriteLiteral(" class=\"btn btn-success radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cl pd-5 bg-1 bk-gray search-wrap\"");

WriteLiteral(" style=\"margin-top:-10px\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">标题：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"resTitle\"");

WriteLiteral(" placeholder=\"请输入标题关键字\"");

WriteLiteral(" class=\"input-text lg inline\"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">所属资料包：</span>\r\n        <select");

WriteLiteral(" name=\"sel_orderstate\"");

WriteLiteral(" id=\"sel_resPage\"");

WriteLiteral(" class=\"select select-box inline\"");

WriteLiteral(">\r\n            <option");

WriteLiteral(" value=\"0\"");

WriteLiteral(">全部</option>\r\n");

            
            #line 27 "..\..\Views\ResPermission\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\ResPermission\Index.cshtml"
             foreach (KeyValueViewModel item in ViewBag.packges)
            {

            
            #line default
            #line hidden
WriteLiteral("                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1797), Tuple.Create("\"", 1814)
            
            #line 29 "..\..\Views\ResPermission\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1805), Tuple.Create<System.Object, System.Int32>(item.Key
            
            #line default
            #line hidden
, 1805), false)
);

WriteLiteral(">");

            
            #line 29 "..\..\Views\ResPermission\Index.cshtml"
                                     Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 30 "..\..\Views\ResPermission\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </select>\r\n        <button");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteLiteral(" class=\"btn btn-success ml-10\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" style=\"border-radius:0px\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe665;</i> 搜索</button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"mt-30\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"dataTables_wrapper no-footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"tbTable_processing\"");

WriteLiteral(" class=\"dataTables_processing\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">处理中...</div>\r\n            <div");

WriteLiteral(" id=\"tbTable_wrapper\"");

WriteLiteral(">\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 42 "..\..\Views\ResPermission\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\ResPermission\Index.cshtml"
     using (Ajax.BeginForm("Get", new { }, new AjaxOptions { OnFailure = "showException", OnSuccess = "initEvent", UpdateTargetId = "tbTable_wrapper", OnBegin = "showLoading", OnComplete = "hideLoading" }, new { id = "searchByRequest" }))
    {
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\ResPermission\Index.cshtml"
   Write(Html.Hidden("PageIndex", Model.PageIndex));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\ResPermission\Index.cshtml"
                                                  
        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\ResPermission\Index.cshtml"
   Write(Html.Hidden("PageSize", Model.PageSize));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\ResPermission\Index.cshtml"
                                                

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"resName\"");

WriteLiteral(" id=\"resName\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n");

WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"packgeId\"");

WriteLiteral(" id=\"resPackgeId\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n");

            
            #line 48 "..\..\Views\ResPermission\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 50 "..\..\Views\ResPermission\Index.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 51 "..\..\Views\ResPermission\Index.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 52 "..\..\Views\ResPermission\Index.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            changeQueryCondition();
            $(""#search"").click(function () {
                changeQueryCondition();
            });

            //输入名称回车查询
            $(""#resTitle"").keypress(function (e) {
                if (e.which == 13) {
                    changeQueryCondition();
                    $(""#search"").focus();
                }
            });
        });


        /*资料-详情*/
        function res_detail(title, url, id) {
            var index = layer.open({
                type: 2,
                title: title,
                area: ['750px', '600px'],
                content: url + ""?id="" + id
            });
        }

        /*保存*/
        function res_save(id) {
            var trjson = getTrJson(id);
            layer.confirm('确认要保存该设置吗？', function (e) {
                $.ajax({
                    url: """);

            
            #line 86 "..\..\Views\ResPermission\Index.cshtml"
                     Write(Url.Action("Save"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    type: \"post\",\r\n                    data: { id: id, json: " +
"trjson },\r\n                    success: function (data) {\r\n                     " +
"   if (data == \"ok\") {\r\n                            layer.alert(\'操作成功！\', {\r\n    " +
"                            icon: 6,\r\n                                closeBtn: " +
"0,\r\n                                yes: function () {\r\n                        " +
"            changeQueryCondition();\r\n                                    layer.c" +
"loseAll();\r\n                                }\r\n                            });\r\n" +
"                        } else if (data == \"error\") {\r\n                         " +
"   layer.alert(\'操作失败！\', { icon: 5 });\r\n                        }\r\n              " +
"          else {\r\n                            layer.alert(data, { icon: 7 });\r\n " +
"                       }\r\n                    },\r\n                    error: fun" +
"ction (data) { layer.alert(\'操作失败！\', { icon: 5 }); }\r\n                })\r\n       " +
"     });\r\n        }\r\n\r\n        function getTrJson(id) {\r\n            var stringB" +
"uild = new StringBuffer();\r\n            stringBuild.append(\"[\");\r\n            va" +
"r conTr = $(\"#tb_tr_\" + id);\r\n            var conTd = conTr.find(\"td[data-id=tb_" +
"td_\" + id + \"]\");\r\n            conTd.each(function () {\r\n                stringB" +
"uild.append(\"{\");\r\n                var mtId = $(this).attr(\"data-bind\");\r\n      " +
"          var perIds = $(this).find(\".selectpicker\").selectpicker(\'val\');\r\n     " +
"           if(perIds==null){perIds=\"\"}\r\n                stringBuild.append(\"\'id\'" +
":\" + mtId+\",\");\r\n                stringBuild.append(\"\'ResPermissionIds\':[\"+perId" +
"s+\"]\");\r\n                stringBuild.append(\"},\");\r\n            })\r\n\r\n          " +
"  var jsStr = trimEnd(stringBuild.toString());\r\n\r\n            jsStr += \"]\";\r\n\r\n " +
"           return jsStr;\r\n        }\r\n\r\n        function initEvent() {\r\n         " +
"   $(\".selectpicker\").selectpicker();\r\n        }\r\n\r\n        //改变筛选条件\r\n        fu" +
"nction changeQueryCondition() {\r\n            $(\"#resName\").val($(\"#resTitle\").va" +
"l());\r\n            $(\"#resPackgeId\").val($(\"#sel_resPage\").val());\r\n            " +
"$(\"#PageIndex\").val(1);//页索引置为1\r\n            $(\"#searchByRequest\").submit();\r\n  " +
"      }\r\n\r\n        //改变索引页\r\n        function changePageIndex(index) {\r\n         " +
"   $(\"#PageIndex\").val(index);\r\n            $(\"#searchByRequest\").submit();\r\n   " +
"     }\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
