#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Areas\manage\Views\Student\Add.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\manage\Views\Student\Add.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\manage\Views\Student\Add.cshtml"
    using HST.Utillity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/Student/Add.cshtml")]
    public partial class _Areas_manage_Views_Student_Add_cshtml : System.Web.Mvc.WebViewPage<StuViewModel>
    {
        public _Areas_manage_Views_Student_Add_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\manage\Views\Student\Add.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Areas\manage\Views\Student\Add.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Areas\manage\Views\Student\Add.cshtml"
Write(Scripts.Render("~/bundles/ajaxAsync"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Areas\manage\Views\Student\Add.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Areas\manage\Views\Student\Add.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .form-horizontal .form-label {\r\n        text-align: right;\r\n    }\r\n</style" +
">\r\n<article");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\manage\Views\Student\Add.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\manage\Views\Student\Add.cshtml"
     using (Ajax.BeginForm("Add", "Student", new { }, new AjaxOptions() { HttpMethod = "Post", OnSuccess = "formSuccess(data)", OnBegin = "disSubmit('sub_btn')", OnComplete = "enSubmit('sub_btn')" }, new { id = "", @class = "form form-horizontal" }))
    {
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\manage\Views\Student\Add.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\manage\Views\Student\Add.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\manage\Views\Student\Add.cshtml"
   Write(Html.HiddenFor(m => m.Id, new { @Value = 0 }));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\manage\Views\Student\Add.cshtml"
                                                      

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>证书类别：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"radio-list\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"radio-inline\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 29 "..\..\Areas\manage\Views\Student\Add.cshtml"
                   Write(Html.RadioButtonFor(m => m.Category, CertificateType.Prize, new { id = "", @checked = "checked" }));

            
            #line default
            #line hidden
WriteLiteral("获奖证书\r\n                    </label>\r\n                    <label");

WriteLiteral(" class=\"radio-inline\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Areas\manage\Views\Student\Add.cshtml"
                   Write(Html.RadioButtonFor(m => m.Category, CertificateType.Train, new { id = "" }));

            
            #line default
            #line hidden
WriteLiteral("学员认证\r\n                    </label>\r\n                </div>\r\n            </div>\r\n " +
"       </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>证书编号：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Areas\manage\Views\Student\Add.cshtml"
           Write(Html.TextBoxFor(m => m.Number, new { placeholder = "请输入证书编号", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Areas\manage\Views\Student\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.Number, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>学员姓名：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Areas\manage\Views\Student\Add.cshtml"
           Write(Html.TextBoxFor(m => m.StudentName, new { placeholder = "请输入学员姓名", @class = "input-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Areas\manage\Views\Student\Add.cshtml"
           Write(Html.ValidationMessageFor(m => m.StudentName, null, new { @class = "error-lable" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 51 "..\..\Areas\manage\Views\Student\Add.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>性别：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"radio-list\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"radio-inline\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 57 "..\..\Areas\manage\Views\Student\Add.cshtml"
                   Write(Html.RadioButtonFor(m => m.Gender, Gender.Female, new { id = "", @checked = "checked" }));

            
            #line default
            #line hidden
WriteLiteral("女\r\n                    </label>\r\n                    <label");

WriteLiteral(" class=\"radio-inline\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 60 "..\..\Areas\manage\Views\Student\Add.cshtml"
                   Write(Html.RadioButtonFor(m => m.Gender, Gender.Male, new { id = "" }));

            
            #line default
            #line hidden
WriteLiteral("男\r\n                    </label>\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral("><span");

WriteLiteral(" class=\"c-red\"");

WriteLiteral(">*</span>所在地区：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Province\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3107), Tuple.Create("\"", 3141)
            
            #line 68 "..\..\Areas\manage\Views\Student\Add.cshtml"
, Tuple.Create(Tuple.Create("", 3115), Tuple.Create<System.Object, System.Int32>(Constant.DEFAULT_PROVINCE
            
            #line default
            #line hidden
, 3115), false)
);

WriteLiteral(" />\r\n                <select");

WriteLiteral(" class=\"select select-box inline\"");

WriteLiteral(" disabled");

WriteLiteral(" style=\"width:45%;background:#eee\"");

WriteLiteral(">\r\n");

            
            #line 70 "..\..\Areas\manage\Views\Student\Add.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Areas\manage\Views\Student\Add.cshtml"
                     foreach (KeyValuePair<int, string> item in ViewBag.AreaProvince)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3390), Tuple.Create("\"", 3407)
            
            #line 72 "..\..\Areas\manage\Views\Student\Add.cshtml"
, Tuple.Create(Tuple.Create("", 3398), Tuple.Create<System.Object, System.Int32>(item.Key
            
            #line default
            #line hidden
, 3398), false)
);

WriteLiteral(">");

            
            #line 72 "..\..\Areas\manage\Views\Student\Add.cshtml"
                                             Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 73 "..\..\Areas\manage\Views\Student\Add.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </select>\r\n                <select");

WriteLiteral(" name=\"City\"");

WriteLiteral(" class=\"select select-box  inline float-right\"");

WriteLiteral(" style=\"width:50%\"");

WriteLiteral(">\r\n");

            
            #line 76 "..\..\Areas\manage\Views\Student\Add.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 76 "..\..\Areas\manage\Views\Student\Add.cshtml"
                     foreach (KeyValuePair<int, string> item in ViewBag.AreaCity)
                {

            
            #line default
            #line hidden
WriteLiteral("                        <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3716), Tuple.Create("\"", 3733)
            
            #line 78 "..\..\Areas\manage\Views\Student\Add.cshtml"
, Tuple.Create(Tuple.Create("", 3724), Tuple.Create<System.Object, System.Int32>(item.Key
            
            #line default
            #line hidden
, 3724), false)
);

WriteLiteral(">");

            
            #line 78 "..\..\Areas\manage\Views\Student\Add.cshtml"
                                             Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 79 "..\..\Areas\manage\Views\Student\Add.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </select>\r\n\r\n            </div>\r\n        </div>\r\n");

            
            #line 84 "..\..\Areas\manage\Views\Student\Add.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"form-label col-xs-3 \"");

WriteLiteral(">状态：</label>\r\n            <div");

WriteLiteral(" class=\"formControls col-xs-6 \"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"select select-box\"");

WriteLiteral(" name=\"State\"");

WriteLiteral(">\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 4080), Tuple.Create("\"", 4114)
            
            #line 89 "..\..\Areas\manage\Views\Student\Add.cshtml"
, Tuple.Create(Tuple.Create("", 4088), Tuple.Create<System.Object, System.Int32>((int)PublishState.Lower
            
            #line default
            #line hidden
, 4088), false)
);

WriteLiteral(">下架</option>\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 4156), Tuple.Create("\"", 4190)
            
            #line 90 "..\..\Areas\manage\Views\Student\Add.cshtml"
, Tuple.Create(Tuple.Create("", 4164), Tuple.Create<System.Object, System.Int32>((int)PublishState.Upper
            
            #line default
            #line hidden
, 4164), false)
);

WriteLiteral(">上架</option>\r\n\r\n                </select>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row cl\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(" class=\"col-xs-6  col-xs-offset-3 col-sm-offset-2 mt-10\"");

WriteLiteral(">\r\n\r\n                <button");

WriteLiteral(" class=\"btn btn-primary radius\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"sub_btn\"");

WriteLiteral(">保存</button>\r\n                <input");

WriteLiteral(" name=\"\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"layer_close();\"");

WriteLiteral(" class=\"btn btn-default radius \"");

WriteLiteral(" value=\"取消\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n");

            
            #line 102 "..\..\Areas\manage\Views\Student\Add.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</article>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function formSuccess(result) {
        if (result != null) {
            if (result.isSuccess) {
                var index = parent.layer.getFrameIndex(window.name);
                layer.alert('保存成功！', {
                    icon: 6,
                    closeBtn: 0,
                    yes: function () {
                        if (parent[1] != null) {
                            parent[pageIndex()].table1.ajax.reload();
                        } else {
                            parent.table1.ajax.reload();
                        }
                        parent.layer.close(index);
                    }
                });
            } else
                layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
        } else
            layer.alert('保存失败！', { icon: 5 });//icon:6为开心图
    }
</script>");

        }
    }
}
#pragma warning restore 1591
