#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HST.Art.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/Account/Login.cshtml")]
    public partial class _Areas_manage_Views_Account_Login_cshtml : System.Web.Mvc.WebViewPage<HST.Art.Web.LoginViewModel>
    {
        public _Areas_manage_Views_Account_Login_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\manage\Views\Account\Login.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<!DOCTYPE HTML>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"renderer\"");

WriteLiteral(" content=\"webkit|ie-comp|ie-stand\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0," +
"user-scalable=no\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-siteapp\"");

WriteLiteral(" />\r\n    <!--[if lt IE 9]>\r\n    <script type=\"text/javascript\" src=\"lib/html5shiv" +
".js\"></script>\r\n    <script type=\"text/javascript\" src=\"lib/respond.min.js\"></sc" +
"ript>\r\n    <![endif]-->\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Areas\manage\Views\Account\Login.cshtml"
Write(Scripts.Render("~/bundles/saos"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Areas\manage\Views\Account\Login.cshtml"
Write(Scripts.Render("~/bundles/validate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Areas\manage\Views\Account\Login.cshtml"
Write(Styles.Render("~/appcss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Areas\manage\Views\Account\Login.cshtml"
Write(Styles.Render("~/login"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!--[if IE 6]>\r\n    <script type=\"text/javascript\" src=\"lib/DD_belatedPNG_0" +
".0.8a-min.js\" ></script>\r\n    <script>DD_belatedPNG.fix(\'*\');</script>\r\n    <![e" +
"ndif]-->\r\n    <title>登录</title>\r\n</head>\r\n<body>\r\n");

            
            #line 30 "..\..\Areas\manage\Views\Account\Login.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\manage\Views\Account\Login.cshtml"
     using (Html.BeginForm("Login", "Account", new { RetrunUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "frmLogin" }))
    {
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\manage\Views\Account\Login.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\manage\Views\Account\Login.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\manage\Views\Account\Login.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\manage\Views\Account\Login.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"wpn\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-data pos\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"/Content/lib/h-ui.admin/images/logo.png\"");

WriteLiteral(" class=\"head-logo\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"change-login\"");

WriteLiteral(">\r\n                        <p");

WriteLiteral(" class=\"account_number on\"");

WriteLiteral(">账号登录</p>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form1\"");

WriteLiteral(">\r\n                        <p");

WriteLiteral(" class=\"p-input pos\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 43 "..\..\Areas\manage\Views\Account\Login.cshtml"
                       Write(Html.TextBoxFor(m => m.Account, new { placeholder = "请输入用户名" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 44 "..\..\Areas\manage\Views\Account\Login.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Account, null, new { @class = "error-lable login-error" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </p>\r\n                        <p");

WriteLiteral(" class=\"p-input pos\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 47 "..\..\Areas\manage\Views\Account\Login.cshtml"
                       Write(Html.PasswordFor(m => m.Password, new { placeholder = "请输入密码"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 48 "..\..\Areas\manage\Views\Account\Login.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Password, null, new { @class = "error-lable login-error" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Areas\manage\Views\Account\Login.cshtml"
                       Write(Html.ValidationMessage("ErrorMessage", null, new { @class = "error-lable login-error", id = "password_error" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </p>\r\n                    </div>\r\n                    <" +
"div");

WriteLiteral(" class=\"r-forget cl\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"javascript:layer.alert(\'请联系管理员对账户进行操作！\', { icon: 8 });\"");

WriteLiteral(" class=\"y\"");

WriteLiteral(">忘记密码</a>\r\n                    </div>\r\n                    <button");

WriteLiteral(" class=\"lang-btn log-btn\"");

WriteLiteral(" id=\"btn_login\"");

WriteLiteral(">登&nbsp;&nbsp;&nbsp;&nbsp;录</button>\r\n                </div>\r\n            </div>\r" +
"\n        </div>\r\n");

            
            #line 59 "..\..\Areas\manage\Views\Account\Login.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral(@"
    <script>
        $(function () {
            $(""#btn_login"").click(function () {
                if ($(""#frmLogin"").valid()) {
                    $(""#frmLogin"").submit();
                    $(""#password_error"").html("""");
                    $(this).html(""正在登录..."").css(""opacity"", ""0.8"").attr(""disabled"", ""disabled"");
                }
            });

            $("".input-text"").keypress(function (e) {
                if (e.which == 13) {
                    $(""#btn_login"").click();
                }
            })
        })
    </script>
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
