#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.SMS.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.SMS.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.Utillity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/MessageRecord/List.cshtml")]
    public partial class _Areas_manage_Views_MessageRecord_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_manage_Views_MessageRecord_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<nav");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span>信息管理  <a");

WriteLiteral(" class=\"btn btn-primary radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral("><div");

WriteLiteral(" class=\"progress-bar\"");

WriteLiteral("><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" style=\"width:25%\"");

WriteLiteral("></span></div></div>\r\n    <div");

WriteLiteral(" class=\"cl pd-10 bg-1 bk-gray mt-10 search-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">订单号：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"sel_filVal\"");

WriteLiteral(" placeholder=\"请输入订单编号\"");

WriteLiteral(" class=\"input-text lg inline \"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">状态：</span>\r\n        <select");

WriteLiteral(" name=\"sel_orderstate\"");

WriteLiteral(" id=\"sel_state\"");

WriteLiteral(" class=\"select select-box sm inline\"");

WriteLiteral(">\r\n            <option");

WriteLiteral(" value=\"-1\"");

WriteLiteral(">全部状态</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 905), Tuple.Create("\"", 940)
            
            #line 14 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 913), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.Unsent
            
            #line default
            #line hidden
, 913), false)
);

WriteLiteral(">未发送</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 975), Tuple.Create("\"", 1014)
            
            #line 15 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 983), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.SendFailed
            
            #line default
            #line hidden
, 983), false)
);

WriteLiteral(">发送失败</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1050), Tuple.Create("\"", 1090)
            
            #line 16 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1058), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.SendSuccess
            
            #line default
            #line hidden
, 1058), false)
);

WriteLiteral(">发送成功</option>\r\n        </select>\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">创建时间：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"WdatePicker()\"");

WriteLiteral(" placeholder=\"创建/导入日期\"");

WriteLiteral(" id=\"sel_date\"");

WriteLiteral(" class=\"input-text inline Wdate\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteLiteral(" class=\"btn btn-success ml-20\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe665;</i> 查询</button>\r\n        <button");

WriteLiteral(" class=\"btn btn-default \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1474), Tuple.Create("\"", 1520)
, Tuple.Create(Tuple.Create("", 1484), Tuple.Create("msg_add(\'新建信息\',\'", 1484), true)
            
            #line 21 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1500), Tuple.Create<System.Object, System.Int32>(Url.Action("Add")
            
            #line default
            #line hidden
, 1500), false)
, Tuple.Create(Tuple.Create("", 1518), Tuple.Create("\')", 1518), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">新建</button>\r\n        <button");

WriteLiteral(" class=\"btn btn-primary \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1589), Tuple.Create("\"", 1641)
, Tuple.Create(Tuple.Create("", 1599), Tuple.Create("msg_import(\'批量导入\',\'", 1599), true)
            
            #line 22 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1618), Tuple.Create<System.Object, System.Int32>(Url.Action("Import")
            
            #line default
            #line hidden
, 1618), false)
, Tuple.Create(Tuple.Create("", 1639), Tuple.Create("\')", 1639), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">导入</button>\r\n        <button");

WriteLiteral(" class=\"btn btn-warning float-right\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1721), Tuple.Create("\"", 1775)
, Tuple.Create(Tuple.Create("", 1731), Tuple.Create("batch_send(\'一键发送\',\'", 1731), true)
            
            #line 23 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1750), Tuple.Create<System.Object, System.Int32>(Url.Action("Progress")
            
            #line default
            #line hidden
, 1750), false)
, Tuple.Create(Tuple.Create("", 1773), Tuple.Create("\')", 1773), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">一键发送</button>\r\n\r\n        <button");

WriteLiteral(" class=\"btn btn-warning \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1848), Tuple.Create("\"", 1893)
, Tuple.Create(Tuple.Create("", 1858), Tuple.Create("msg_test(\'", 1858), true)
            
            #line 25 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1868), Tuple.Create<System.Object, System.Int32>(Url.Action("Progress")
            
            #line default
            #line hidden
, 1868), false)
, Tuple.Create(Tuple.Create("", 1891), Tuple.Create("\')", 1891), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">测试</button>\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"is_admin\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1964), Tuple.Create("\"", 1991)
            
            #line 26 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1972), Tuple.Create<System.Object, System.Int32>(ViewBag.IsSupAdmin
            
            #line default
            #line hidden
, 1972), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"mt-10\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"tbTable\"");

WriteLiteral(" class=\"table table-border table-bordered table-bg table-sort\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr");

WriteLiteral(" class=\"text-c\"");

WriteLiteral(">\r\n                    <th");

WriteLiteral(" width=\"8%\"");

WriteLiteral(">序号</th>\r\n                    <th");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">订单编号</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">手机号</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">订单日期</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">状态</th>\r\n                    <th");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">推送日期</th>\r\n                    <th");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">创建时间</th>\r\n                    <th");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">操作</th>\r\n                </tr>\r\n            </thead>\r\n        </table>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var table1 = null;
        $(function () {
            table1 = initializeTable();
            $(""#search"").click(function () {
                table1.ajax.reload();
            });

            //输入名称回车查询
            $(""#sel_filVal"").keypress(function (e) {
                if (e.which == 13) {
                    table1.ajax.reload();
                    $(""#search"").focus();
                }
            });

        });

        /*编辑*/
        function msg_edit(title, url, id) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['600px', '480px'],
                content: url + ""?id="" + id
            });
        }

        /*添加*/
        function msg_add(title, url) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['600px', '480px'],
                content: url
            });
        }

        function msg_import(title, url) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['750px', '500px'],
                content: url
            });
        }


        function msg_test(url) {
            $.ajax({
                url: '");

            
            #line 97 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                 Write(Url.Action("BatchSend"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                type: \"post\",\r\n                async: false,\r\n               " +
" success: function (data) {\r\n                    if (data.isSuccess) {\r\n        " +
"                //clearInterval(sitv);\r\n                        //var index = pa" +
"rent.layer.getFrameIndex(window.name);\r\n                        top.layer.alert(" +
"\'发送成功！\', {\r\n                            icon: 6,\r\n                            cl" +
"oseBtn: 0,\r\n                            yes: function () {\r\n                    " +
"            if (parent[1] != null) {\r\n                                    parent" +
"[pageIndex()].table1.ajax.reload();\r\n                                } else if (" +
"parent.table1 != null) {\r\n                                    parent.table1.ajax" +
".reload();\r\n                                } else {\r\n                          " +
"          parent[0].table1.ajax.reload();\r\n                                }\r\n  " +
"                              parent.layer.closeAll();\r\n                        " +
"    }\r\n                        });\r\n                    } else if (data.message " +
"!= null) {\r\n                        top.layer.alert(data.message, { icon: 8 });\r" +
"\n                    } else {\r\n                        top.layer.alert(\'发送失败！\', " +
"{ icon: 5 });\r\n                    }\r\n                },\r\n                error:" +
" function (data) { top.layer.alert(\'发送失败！\', { icon: 5 }); }\r\n            })\r\n   " +
"     }\r\n\r\n        /*发送*/\r\n        function batch_send(title, action) {\r\n        " +
"    var aaa= top.layer.confirm(\'确认要\' + title + \'吗？\', function (e) {\r\n           " +
"     top.layer.close(aaa);\r\n                var index = top.layer.open({\r\n      " +
"              type: 2,\r\n                    title: \"正在发送中...\",\r\n                " +
"    area: [\'750px\', \'200px\'],\r\n                    content: action\r\n            " +
"    });\r\n        \r\n     \r\n\r\n            });\r\n        }\r\n\r\n        function initi" +
"alizeTable() {\r\n            var dataTable = $(\'#tbTable\').DataTable({\r\n         " +
"       \"serverSide\": true,\r\n                \"ajax\": {\r\n                    \"url\"" +
": \"");

            
            #line 148 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                       Write(Url.Action("GetJsonData"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    \"type\": \"post\",\r\n                    \"data\": function (da" +
"ta) {\r\n                        data.pageIndex = (data.start / data.length) + 1;\r" +
"\n                        data.SendState = $(\"#sel_state\").val();\r\n              " +
"          data.MsgId = $(\"#sel_filVal\").val();\r\n                        data.Cre" +
"ateDate = $(\"#sel_date\").val();\r\n                    }\r\n                },\r\n    " +
"            \"columns\": [\r\n                      { \"defaultContent\": \"\" },\r\n     " +
"                 { \"mDataProp\": \"Number\" },\r\n                       { \"mDataProp" +
"\": \"Phone\" },\r\n                      { \"mDataProp\": \"OrderDate\" },\r\n            " +
"          { \"mDataProp\": \"State\" },\r\n                      { \"mDataProp\": \"SendD" +
"ate\" },\r\n                      { \"mDataProp\": \"CreateTime\" },\r\n                 " +
"     { \"defaultContent\": \"\" }\r\n\r\n                ],\r\n                \"columnDefs" +
"\": [\r\n                 {\r\n                     \"targets\": [4],\r\n                " +
"     \"data\": \"State\",\r\n                     \"render\": function (data, type, full" +
") {\r\n                         var result = data;\r\n                         if (d" +
"ata > 1) {\r\n                             result = \"<span class=\\\"label label-suc" +
"cess radius\\\">发送成功</span>\";\r\n                         } else if (data < 1) {\r\n  " +
"                           result = \"<span class=\\\"label label-primary radius\\\">" +
"未发送</span>\";\r\n                         } else {\r\n                             re" +
"sult = \"<span class=\\\"label label-danger radius\\\">发送失败</span>\";\r\n               " +
"          }\r\n\r\n                         return result;\r\n                     }\r\n" +
"                 },\r\n        {\r\n            \"targets\": [-1],\r\n            \"data\"" +
": \"Id\",\r\n            \"render\": function (data, type, full) {\r\n                va" +
"r isAdmin = $(\"#is_admin\").val();\r\n                var tmpString = \"<button clas" +
"s=\'btn btn-primary size-MINI\' onclick=\\\"msg_edit(\'修改信息\',\'");

            
            #line 190 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                 Write(Url.Action("Edit"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>编辑</button>\";\r\n                if (full.State == " +
"0)\r\n                    tmpString += \"<button class=\'btn btn-warning size-MINI\' " +
"onclick=\\\"obj_send(\'发送\',\'");

            
            #line 192 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                Write(Url.Action("Send"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>发送</button>\";\r\n                else if (full.Stat" +
"e == 1)\r\n                    tmpString += \"<button class=\'btn btn-warning size-M" +
"INI\' onclick=\\\"obj_send(\'重新发送\',\'");

            
            #line 194 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                  Write(Url.Action("Send"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>重新发送</button>\";\r\n                if (isAdmin)\r\n  " +
"                  tmpString += \"<button class=\'btn btn-danger size-MINI\' onclick" +
"=\\\"obj_del(\'消息\',\'");

            
            #line 196 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                              Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>删除</button>\";\r\n\r\n                return tmpString" +
";\r\n            }\r\n        }\r\n                ],\r\n                \"fnDrawCallback" +
"\": function () {\r\n                    var api = this.api();\r\n                   " +
" var startIndex = api.context[0]._iDisplayStart;\r\n                    api.column" +
"(0).nodes().each(function (cell, i) {\r\n                        cell.innerHTML = " +
"startIndex + i + 1;\r\n                    });\r\n                },\r\n              " +
"  \"rowCallback\": function (row, data, displayIndex) {\r\n                    $(row" +
").attr(\"class\", \"text-c\");\r\n                    $(row).children(\'td\').eq(7).attr" +
"(\"class\", \"td-status\");\r\n                    $(row).children(\'td\').eq(10).attr(\"" +
"class\", \"td-manage\");\r\n                },\r\n                \"initComplete\": funct" +
"ion (settings, json) {\r\n\r\n                },\r\n                language: {\r\n     " +
"               lengthMenu: \'\',\r\n                    loadingRecords: \'数据加载中...\',\r" +
"\n                    paginate: {\r\n                        previous: \"上一页\",\r\n    " +
"                    next: \"下一页\",\r\n                        first: \"\",\r\n          " +
"              last: \"\"\r\n                    },\r\n                    zeroRecords:" +
" \"暂无数据\",\r\n\r\n                    info: \"<span class=\'pagesStyle\'>总共<span class=\'r" +
"ecordsStyle\'> _TOTAL_ 条,计 _PAGES_ </span>页，当前显示 _START_ -- _END_ 条记录 </span>\",\r\n" +
"                    infoEmpty: \"0条记录\",\r\n                    infoFiltered: \"\"\r\n  " +
"              },\r\n                \"searching\": false,\r\n                \"ordering" +
"\": false,\r\n                \"autoWidth\": false,\r\n                \"iDisplayLength\"" +
": 10,\r\n                \"processing\": true,\r\n                //destroy: true, //C" +
"annot reinitialise DataTable,解决重新加载表格内容问题\r\n\r\n            });\r\n            return" +
" dataTable;\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
