#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.SMS.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.SMS.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.Utillity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/MessageRecord/List.cshtml")]
    public partial class _Areas_manage_Views_MessageRecord_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_manage_Views_MessageRecord_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<nav");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span>信息管理  <a");

WriteLiteral(" class=\"btn btn-primary radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cl pd-10 bg-1 bk-gray mt-10 search-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">订单号：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"sel_filVal\"");

WriteLiteral(" placeholder=\"请输入订单编号\"");

WriteLiteral(" class=\"input-text lg inline \"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">状态：</span>\r\n        <select");

WriteLiteral(" name=\"sel_orderstate\"");

WriteLiteral(" id=\"sel_state\"");

WriteLiteral(" class=\"select select-box sm inline\"");

WriteLiteral(">\r\n            <option");

WriteLiteral(" value=\"-1\"");

WriteLiteral(">全部状态</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 792), Tuple.Create("\"", 827)
            
            #line 13 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 800), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.Unsent
            
            #line default
            #line hidden
, 800), false)
);

WriteLiteral(">未发送</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 862), Tuple.Create("\"", 901)
            
            #line 14 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 870), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.SendFailed
            
            #line default
            #line hidden
, 870), false)
);

WriteLiteral(">发送失败</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 937), Tuple.Create("\"", 979)
            
            #line 15 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 945), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.ReceiveFailed
            
            #line default
            #line hidden
, 945), false)
);

WriteLiteral(">接收失败</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1015), Tuple.Create("\"", 1055)
            
            #line 16 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1023), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.SendSuccess
            
            #line default
            #line hidden
, 1023), false)
);

WriteLiteral(">发送成功</option>\r\n        </select>\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">创建时间：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"WdatePicker()\"");

WriteLiteral(" placeholder=\"创建/导入日期\"");

WriteLiteral(" id=\"sel_date\"");

WriteLiteral(" class=\"input-text inline Wdate\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteLiteral(" class=\"btn btn-success ml-20\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe665;</i> 查询</button>\r\n        ");

WriteLiteral("\r\n        <button");

WriteLiteral(" class=\"btn btn-primary \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1558), Tuple.Create("\"", 1610)
, Tuple.Create(Tuple.Create("", 1568), Tuple.Create("msg_import(\'批量导入\',\'", 1568), true)
            
            #line 22 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1587), Tuple.Create<System.Object, System.Int32>(Url.Action("Import")
            
            #line default
            #line hidden
, 1587), false)
, Tuple.Create(Tuple.Create("", 1608), Tuple.Create("\')", 1608), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">导入</button>\r\n        <button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1678), Tuple.Create("\"", 1797)
, Tuple.Create(Tuple.Create("", 1688), Tuple.Create("batch_send(\'一键发送\',\'", 1688), true)
            
            #line 23 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1707), Tuple.Create<System.Object, System.Int32>(Url.Action("Progress", new { state = (int)MsgSendState.Unsent })
            
            #line default
            #line hidden
, 1707), false)
, Tuple.Create(Tuple.Create("", 1772), Tuple.Create("\',\'", 1772), true)
            
            #line 23 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 1775), Tuple.Create<System.Object, System.Int32>(MsgSendState.Unsent
            
            #line default
            #line hidden
, 1775), false)
, Tuple.Create(Tuple.Create("", 1795), Tuple.Create("\')", 1795), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">一键发送</button>\r\n        <div");

WriteLiteral(" class=\"dropdown btn-group float-right\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-default dropdown-toggle\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n                更多 <i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe6d5;</i>\r\n            </button>\r\n            <div");

WriteLiteral(" class=\"dropdown-menu right\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"javascript:;\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2168), Tuple.Create("\"", 2214)
, Tuple.Create(Tuple.Create("", 2178), Tuple.Create("msg_add(\'新建信息\',\'", 2178), true)
            
            #line 29 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
      , Tuple.Create(Tuple.Create("", 2194), Tuple.Create<System.Object, System.Int32>(Url.Action("Add")
            
            #line default
            #line hidden
, 2194), false)
, Tuple.Create(Tuple.Create("", 2212), Tuple.Create("\')", 2212), true)
);

WriteLiteral(">新建信息</a>\r\n                <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" onclick=\"msg_Righting()\"");

WriteLiteral(">冲正</a>\r\n                <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"javascript:;\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2380), Tuple.Create("\"", 2507)
, Tuple.Create(Tuple.Create("", 2390), Tuple.Create("batch_send(\'一键发送\',\'", 2390), true)
            
            #line 31 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
         , Tuple.Create(Tuple.Create("", 2409), Tuple.Create<System.Object, System.Int32>(Url.Action("Progress", new { state = (int)MsgSendState.SendFailed })
            
            #line default
            #line hidden
, 2409), false)
, Tuple.Create(Tuple.Create("", 2478), Tuple.Create("\',\'", 2478), true)
            
            #line 31 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                 , Tuple.Create(Tuple.Create("", 2481), Tuple.Create<System.Object, System.Int32>(MsgSendState.SendFailed
            
            #line default
            #line hidden
, 2481), false)
, Tuple.Create(Tuple.Create("", 2505), Tuple.Create("\')", 2505), true)
);

WriteLiteral(">失败批量发送</a>\r\n            </div>\r\n        </div>\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"is_admin\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2599), Tuple.Create("\"", 2626)
            
            #line 34 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 2607), Tuple.Create<System.Object, System.Int32>(ViewBag.IsSupAdmin
            
            #line default
            #line hidden
, 2607), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"mt-10\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"tbTable\"");

WriteLiteral(" class=\"table table-border table-bordered table-bg table-sort\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr");

WriteLiteral(" class=\"text-c\"");

WriteLiteral(">\r\n                    <th");

WriteLiteral(" width=\"5%\"");

WriteLiteral(">序号</th>\r\n                    <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">订单编号</th>\r\n                    <th");

WriteLiteral(" width=\"18%\"");

WriteLiteral(">商品名称</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">手机号</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">订单日期</th>\r\n                    <th");

WriteLiteral(" width=\"8%\"");

WriteLiteral(">状态</th>\r\n                    <th");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">推送日期</th>\r\n                    <th");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">创建时间</th>\r\n                    <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">操作</th>\r\n                </tr>\r\n            </thead>\r\n        </table>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var table1 = null;\r\n        $(function () {\r\n            table1 = init" +
"ializeTable();\r\n            $(\"#search\").click(function () {\r\n                ta" +
"ble1.ajax.reload();\r\n            });\r\n\r\n            //输入名称回车查询\r\n            $(\"#" +
"sel_filVal\").keypress(function (e) {\r\n                if (e.which == 13) {\r\n    " +
"                table1.ajax.reload();\r\n                    $(\"#search\").focus();" +
"\r\n                }\r\n            });\r\n        });\r\n\r\n        /*编辑*/\r\n        fun" +
"ction msg_edit(title, url, id) {\r\n            var index = top.layer.open({\r\n    " +
"            type: 2,\r\n                title: title,\r\n                area: [\'600" +
"px\', \'480px\'],\r\n                content: url + \"?id=\" + id\r\n            });\r\n   " +
"     }\r\n\r\n        /*添加*/\r\n        function msg_add(title, url) {\r\n            va" +
"r index = top.layer.open({\r\n                type: 2,\r\n                title: tit" +
"le,\r\n                area: [\'600px\', \'480px\'],\r\n                content: url\r\n  " +
"          });\r\n        }\r\n\r\n        function msg_import(title, url) {\r\n         " +
"   var index = top.layer.open({\r\n                type: 2,\r\n                title" +
": title,\r\n                area: [\'750px\', \'500px\'],\r\n                content: ur" +
"l\r\n            });\r\n        }\r\n\r\n        /*冲正*/\r\n        function msg_Righting()" +
" {\r\n            top.layer.confirm(\'冲正时不可进行其他操作\', function (e) {\r\n               " +
" var loadIndex = top.layer.msg(\'数据正在处理中,请稍后...\', {\r\n                    icon: 16" +
", shade: 0.4, time: 0\r\n                });\r\n\r\n                $.ajax({\r\n        " +
"            url: \'");

            
            #line 110 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                     Write(Url.Action("Righting"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    type: ""post"",
                    success: function (data) {
                        top.layer.close(loadIndex);
                        if (data.isSuccess) {
                            top.layer.alert('操作成功！', {
                                icon: 6,
                                closeBtn: 0,
                                yes: function () {
                                    if (parent[1] != null) {
                                        parent[pageIndex()].table1.ajax.reload();
                                    } else if (parent.table1 != null) {
                                        parent.table1.ajax.reload();
                                    } else {
                                        parent[0].table1.ajax.reload();
                                    }
                                    parent.layer.closeAll();
                                }
                            });
                        } else {
                            top.layer.alert('操作失败！', { icon: 5 });
                        }
                    },
                    error: function (data) { top.layer.close(loadIndex); top.layer.alert('操作失败！', { icon: 5 }); }
                })
            });
        }

        /*发送*/
        function batch_send(title, action, state) {
            $.ajax({
                url: '");

            
            #line 141 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                 Write(Url.Action("CheckSupportSend"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: ""get"",
                data: { state: state },
                success: function (data) {
                    if (data.isSuccess) {
                        top.layer.confirm('确认要' + title + '吗？', function (e) {
                            var index = top.layer.open({
                                type: 2,
                                title: ""正在发送中..."",
                                area: ['750px', '200px'],
                                content: action
                            });
                        });
                    } else {
                        top.layer.alert(data.message, { icon: 8 });
                    }
                },
                error: function (data) {
                    top.layer.alert('操作失败！' + data, { icon: 5 });
                }
            })
        }

        function initializeTable() {
            var dataTable = $('#tbTable').DataTable({
                ""serverSide"": true,
                ""ajax"": {
                    ""url"": """);

            
            #line 168 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                       Write(Url.Action("GetJsonData"));

            
            #line default
            #line hidden
WriteLiteral(@""",
                    ""type"": ""post"",
                    ""data"": function (data) {
                        data.pageIndex = (data.start / data.length) + 1;
                        data.SendState = $(""#sel_state"").val();
                        data.MsgId = $(""#sel_filVal"").val();
                        data.CreateDate = $(""#sel_date"").val();
                    }
                },
                ""columns"": [
                      { ""defaultContent"": """" },
                      { ""mDataProp"": ""Number"" },
                        { ""mDataProp"": ""OrderName"" },
                         { ""mDataProp"": ""Phone"" },
                      { ""mDataProp"": ""OrderDate"" },
                      { ""mDataProp"": ""State"" },
                      { ""mDataProp"": ""SendDate"" },
                      { ""mDataProp"": ""CreateTime"" },
                      { ""defaultContent"": """" }

                ],
                ""columnDefs"": [
                 {
                     ""targets"": [5],
                     ""data"": ""State"",
                     ""render"": function (data, type, full) {
                         var result = data;
                         if (data == '");

            
            #line 195 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                  Write((int)MsgSendState.ReceiveFailed);

            
            #line default
            #line hidden
WriteLiteral("\') {\r\n                             result = \"<span class=\\\"label label-warning ra" +
"dius\\\">接收失败</span>\";\r\n                         }\r\n                         else " +
"if (data == \'");

            
            #line 198 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                       Write((int)MsgSendState.SendSuccess);

            
            #line default
            #line hidden
WriteLiteral("\') {\r\n                             result = \"<span class=\\\"label label-success ra" +
"dius\\\">发送成功</span>\";\r\n                         } else if (data == \'");

            
            #line 200 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                         Write((int)MsgSendState.Unsent);

            
            #line default
            #line hidden
WriteLiteral(@"') {
                             result = ""<span class=\""label label-primary radius\"">未发送</span>"";
                         } else {
                             result = ""<span class=\""label label-danger radius\"">发送失败</span>"";
                         }

                         return result;
                     }
                 },
        {
            ""targets"": [-1],
            ""data"": ""Id"",
            ""render"": function (data, type, full) {
                var isAdmin = $(""#is_admin"").val();
                var tmpString = ""<button class='btn btn-primary size-MINI' onclick=\""msg_edit('修改信息','");

            
            #line 214 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                 Write(Url.Action("Edit"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>编辑</button>\";\r\n                if (full.State == " +
"0)\r\n                    tmpString += \"<button class=\'btn btn-warning size-MINI\' " +
"onclick=\\\"obj_send(\'发送\',\'");

            
            #line 216 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                Write(Url.Action("Send"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>发送</button>\";\r\n                else if (full.Stat" +
"e == 1)\r\n                    tmpString += \"<button class=\'btn btn-warning size-M" +
"INI\' onclick=\\\"obj_send(\'重新发送\',\'");

            
            #line 218 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                  Write(Url.Action("Send"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>重新发送</button>\";\r\n                if (isAdmin)\r\n  " +
"                  tmpString += \"<button class=\'btn btn-danger size-MINI\' onclick" +
"=\\\"obj_del(\'消息\',\'");

            
            #line 220 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                              Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>删除</button>\";\r\n\r\n                return tmpString" +
";\r\n            }\r\n        }\r\n                ],\r\n                \"fnDrawCallback" +
"\": function () {\r\n                    var api = this.api();\r\n                   " +
" var startIndex = api.context[0]._iDisplayStart;\r\n                    api.column" +
"(0).nodes().each(function (cell, i) {\r\n                        cell.innerHTML = " +
"startIndex + i + 1;\r\n                    });\r\n                },\r\n              " +
"  \"rowCallback\": function (row, data, displayIndex) {\r\n                    $(row" +
").attr(\"class\", \"text-c\");\r\n                    $(row).children(\'td\').eq(7).attr" +
"(\"class\", \"td-status\");\r\n                    $(row).children(\'td\').eq(10).attr(\"" +
"class\", \"td-manage\");\r\n                },\r\n                \"initComplete\": funct" +
"ion (settings, json) {\r\n\r\n                },\r\n                language: {\r\n     " +
"               lengthMenu: \'\',\r\n                    loadingRecords: \'数据加载中...\',\r" +
"\n                    paginate: {\r\n                        previous: \"上一页\",\r\n    " +
"                    next: \"下一页\",\r\n                        first: \"\",\r\n          " +
"              last: \"\"\r\n                    },\r\n                    zeroRecords:" +
" \"暂无数据\",\r\n\r\n                    info: \"<span class=\'pagesStyle\'>总共<span class=\'r" +
"ecordsStyle\'> _TOTAL_ 条,计 _PAGES_ </span>页，当前显示 _START_ -- _END_ 条记录 </span>\",\r\n" +
"                    infoEmpty: \"0条记录\",\r\n                    infoFiltered: \"\"\r\n  " +
"              },\r\n                \"searching\": false,\r\n                \"ordering" +
"\": false,\r\n                \"autoWidth\": false,\r\n                \"iDisplayLength\"" +
": 50,\r\n                \"processing\": true,\r\n                //destroy: true, //C" +
"annot reinitialise DataTable,解决重新加载表格内容问题\r\n\r\n            });\r\n            return" +
" dataTable;\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
