#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.SMS.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.SMS.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
    using ZT.Utillity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/manage/Views/MessageRecord/List.cshtml")]
    public partial class _Areas_manage_Views_MessageRecord_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_manage_Views_MessageRecord_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<nav");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe67f;</i> 首页 <span");

WriteLiteral(" class=\"c-gray en\"");

WriteLiteral(">&gt;</span>信息管理  <a");

WriteLiteral(" class=\"btn btn-primary radius r\"");

WriteLiteral(" style=\"line-height:1.6em;margin-top:3px\"");

WriteLiteral(" href=\"javascript:location.replace(location.href);\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe68f;</i></a></nav>\r\n<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cl pd-10 bg-1 bk-gray mt-10 search-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">订单号：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"sel_filVal\"");

WriteLiteral(" placeholder=\"请输入订单编号\"");

WriteLiteral(" class=\"input-text lg inline \"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">状态：</span>\r\n        <select");

WriteLiteral(" name=\"sel_orderstate\"");

WriteLiteral(" id=\"sel_state\"");

WriteLiteral(" class=\"select select-box sm inline\"");

WriteLiteral(">\r\n            <option");

WriteLiteral(" value=\"-1\"");

WriteLiteral(">全部状态</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 792), Tuple.Create("\"", 827)
            
            #line 13 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 800), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.Unsent
            
            #line default
            #line hidden
, 800), false)
);

WriteLiteral(">未发送</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 862), Tuple.Create("\"", 901)
            
            #line 14 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 870), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.SendFailed
            
            #line default
            #line hidden
, 870), false)
);

WriteLiteral(">发送失败</option>\r\n            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 937), Tuple.Create("\"", 977)
            
            #line 15 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 945), Tuple.Create<System.Object, System.Int32>((int)MsgSendState.SendSuccess
            
            #line default
            #line hidden
, 945), false)
);

WriteLiteral(">发送成功</option>\r\n        </select>\r\n        <span");

WriteLiteral(" class=\"label-inline\"");

WriteLiteral(">创建时间：</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"WdatePicker()\"");

WriteLiteral(" placeholder=\"创建/导入日期\"");

WriteLiteral(" id=\"sel_date\"");

WriteLiteral(" class=\"input-text inline Wdate\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" name=\"search\"");

WriteLiteral(" id=\"search\"");

WriteLiteral(" class=\"btn btn-success ml-20\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe665;</i> 查询</button>\r\n        ");

WriteLiteral("\r\n        <button");

WriteLiteral(" class=\"btn btn-primary \"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1480), Tuple.Create("\"", 1532)
, Tuple.Create(Tuple.Create("", 1490), Tuple.Create("msg_import(\'批量导入\',\'", 1490), true)
            
            #line 21 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1509), Tuple.Create<System.Object, System.Int32>(Url.Action("Import")
            
            #line default
            #line hidden
, 1509), false)
, Tuple.Create(Tuple.Create("", 1530), Tuple.Create("\')", 1530), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">导入</button>\r\n        <button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1600), Tuple.Create("\"", 1719)
, Tuple.Create(Tuple.Create("", 1610), Tuple.Create("batch_send(\'一键发送\',\'", 1610), true)
            
            #line 22 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 1629), Tuple.Create<System.Object, System.Int32>(Url.Action("Progress", new { state = (int)MsgSendState.Unsent })
            
            #line default
            #line hidden
, 1629), false)
, Tuple.Create(Tuple.Create("", 1694), Tuple.Create("\',\'", 1694), true)
            
            #line 22 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 1697), Tuple.Create<System.Object, System.Int32>(MsgSendState.Unsent
            
            #line default
            #line hidden
, 1697), false)
, Tuple.Create(Tuple.Create("", 1717), Tuple.Create("\')", 1717), true)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(">一键发送</button>\r\n\r\n        ");

WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"dropdown btn-group float-right\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-default dropdown-toggle\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n                更多 <i");

WriteLiteral(" class=\"Hui-iconfont\"");

WriteLiteral(">&#xe6d5;</i>\r\n            </button>\r\n            <div");

WriteLiteral(" class=\"dropdown-menu right\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"javascript:;\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2210), Tuple.Create("\"", 2256)
, Tuple.Create(Tuple.Create("", 2220), Tuple.Create("msg_add(\'新建信息\',\'", 2220), true)
            
            #line 30 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
      , Tuple.Create(Tuple.Create("", 2236), Tuple.Create<System.Object, System.Int32>(Url.Action("Add")
            
            #line default
            #line hidden
, 2236), false)
, Tuple.Create(Tuple.Create("", 2254), Tuple.Create("\')", 2254), true)
);

WriteLiteral(">新建信息</a>\r\n                ");

WriteLiteral("\r\n                <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"javascript:;\"");

WriteAttribute("onclick", Tuple.Create("onclick=\"", 2412), Tuple.Create("\"", 2538)
, Tuple.Create(Tuple.Create("", 2421), Tuple.Create("batch_send(\'一键发送\',\'", 2421), true)
            
            #line 32 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
        , Tuple.Create(Tuple.Create("", 2440), Tuple.Create<System.Object, System.Int32>(Url.Action("Progress", new { state = (int)MsgSendState.SendFailed })
            
            #line default
            #line hidden
, 2440), false)
, Tuple.Create(Tuple.Create("", 2509), Tuple.Create("\',\'", 2509), true)
            
            #line 32 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                , Tuple.Create(Tuple.Create("", 2512), Tuple.Create<System.Object, System.Int32>(MsgSendState.SendFailed
            
            #line default
            #line hidden
, 2512), false)
, Tuple.Create(Tuple.Create("", 2536), Tuple.Create("\')", 2536), true)
);

WriteLiteral(">失败批量发送</a>\r\n            </div>\r\n        </div>\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"is_admin\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2630), Tuple.Create("\"", 2657)
            
            #line 35 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
, Tuple.Create(Tuple.Create("", 2638), Tuple.Create<System.Object, System.Int32>(ViewBag.IsSupAdmin
            
            #line default
            #line hidden
, 2638), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"mt-10\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"tbTable\"");

WriteLiteral(" class=\"table table-border table-bordered table-bg table-sort\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr");

WriteLiteral(" class=\"text-c\"");

WriteLiteral(">\r\n                    <th");

WriteLiteral(" width=\"5%\"");

WriteLiteral(">序号</th>\r\n                    <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">订单编号</th>\r\n                    <th");

WriteLiteral(" width=\"18%\"");

WriteLiteral(">商品名称</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">手机号</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">订单日期</th>\r\n                    <th");

WriteLiteral(" width=\"8%\"");

WriteLiteral(">状态</th>\r\n                    <th");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">推送日期</th>\r\n                    <th");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">创建时间</th>\r\n                    <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">操作</th>\r\n                </tr>\r\n            </thead>\r\n        </table>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var table1 = null;
        $(function () {
            table1 = initializeTable();
            $(""#search"").click(function () {
                table1.ajax.reload();
            });

            //输入名称回车查询
            $(""#sel_filVal"").keypress(function (e) {
                if (e.which == 13) {
                    table1.ajax.reload();
                    $(""#search"").focus();
                }
            });
        });

        /*编辑*/
        function msg_edit(title, url, id) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['600px', '480px'],
                content: url + ""?id="" + id
            });
        }

        /*添加*/
        function msg_add(title, url) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['600px', '480px'],
                content: url
            });
        }

        function msg_import(title, url) {
            var index = top.layer.open({
                type: 2,
                title: title,
                area: ['750px', '500px'],
                content: url
            });
        }


        function msg_test(url) {
            alert(1);
        }

        /*发送*/
        function batch_send(title, action, state) {
            $.ajax({
                url: '");

            
            #line 111 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                 Write(Url.Action("CheckSupportSend"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: ""get"",
                data: { state: state },
                success: function (data) {
                    if (data.isSuccess) {
                        top.layer.confirm('确认要' + title + '吗？', function (e) {
                            var index = top.layer.open({
                                type: 2,
                                title: ""正在发送中..."",
                                area: ['750px', '200px'],
                                content: action
                            });
                        });
                    } else {
                        top.layer.alert(data.message, { icon: 8 });
                    }
                },
                error: function (data) {
                    top.layer.alert('操作失败！' + data, { icon: 5 });
                }
            })        
        }

        function initializeTable() {
            var dataTable = $('#tbTable').DataTable({
                ""serverSide"": true,
                ""ajax"": {
                    ""url"": """);

            
            #line 138 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                       Write(Url.Action("GetJsonData"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    \"type\": \"post\",\r\n                    \"data\": function (da" +
"ta) {\r\n                        data.pageIndex = (data.start / data.length) + 1;\r" +
"\n                        data.SendState = $(\"#sel_state\").val();\r\n              " +
"          data.MsgId = $(\"#sel_filVal\").val();\r\n                        data.Cre" +
"ateDate = $(\"#sel_date\").val();\r\n                    }\r\n                },\r\n    " +
"            \"columns\": [\r\n                      { \"defaultContent\": \"\" },\r\n     " +
"                 { \"mDataProp\": \"Number\" },\r\n                        { \"mDataPro" +
"p\": \"OrderName\" },\r\n                         { \"mDataProp\": \"Phone\" },\r\n        " +
"              { \"mDataProp\": \"OrderDate\" },\r\n                      { \"mDataProp\"" +
": \"State\" },\r\n                      { \"mDataProp\": \"SendDate\" },\r\n              " +
"        { \"mDataProp\": \"CreateTime\" },\r\n                      { \"defaultContent\"" +
": \"\" }\r\n\r\n                ],\r\n                \"columnDefs\": [\r\n                 " +
"{\r\n                     \"targets\": [5],\r\n                     \"data\": \"State\",\r\n" +
"                     \"render\": function (data, type, full) {\r\n                  " +
"       var result = data;\r\n                         if (data > 1) {\r\n           " +
"                  result = \"<span class=\\\"label label-success radius\\\">发送成功</spa" +
"n>\";\r\n                         } else if (data < 1) {\r\n                         " +
"    result = \"<span class=\\\"label label-primary radius\\\">未发送</span>\";\r\n         " +
"                } else {\r\n                             result = \"<span class=\\\"l" +
"abel label-danger radius\\\">发送失败</span>\";\r\n                         }\r\n\r\n        " +
"                 return result;\r\n                     }\r\n                 },\r\n  " +
"      {\r\n            \"targets\": [-1],\r\n            \"data\": \"Id\",\r\n            \"r" +
"ender\": function (data, type, full) {\r\n                var isAdmin = $(\"#is_admi" +
"n\").val();\r\n                var tmpString = \"<button class=\'btn btn-primary size" +
"-MINI\' onclick=\\\"msg_edit(\'修改信息\',\'");

            
            #line 181 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                 Write(Url.Action("Edit"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>编辑</button>\";\r\n                if (full.State == " +
"0)\r\n                    tmpString += \"<button class=\'btn btn-warning size-MINI\' " +
"onclick=\\\"obj_send(\'发送\',\'");

            
            #line 183 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                Write(Url.Action("Send"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>发送</button>\";\r\n                else if (full.Stat" +
"e == 1)\r\n                    tmpString += \"<button class=\'btn btn-warning size-M" +
"INI\' onclick=\\\"obj_send(\'重新发送\',\'");

            
            #line 185 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                                  Write(Url.Action("Send"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>重新发送</button>\";\r\n                if (isAdmin)\r\n  " +
"                  tmpString += \"<button class=\'btn btn-danger size-MINI\' onclick" +
"=\\\"obj_del(\'消息\',\'");

            
            #line 187 "..\..\Areas\manage\Views\MessageRecord\List.cshtml"
                                                                                              Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral("\',\" + data + \")\\\" type=\'button\'>删除</button>\";\r\n\r\n                return tmpString" +
";\r\n            }\r\n        }\r\n                ],\r\n                \"fnDrawCallback" +
"\": function () {\r\n                    var api = this.api();\r\n                   " +
" var startIndex = api.context[0]._iDisplayStart;\r\n                    api.column" +
"(0).nodes().each(function (cell, i) {\r\n                        cell.innerHTML = " +
"startIndex + i + 1;\r\n                    });\r\n                },\r\n              " +
"  \"rowCallback\": function (row, data, displayIndex) {\r\n                    $(row" +
").attr(\"class\", \"text-c\");\r\n                    $(row).children(\'td\').eq(7).attr" +
"(\"class\", \"td-status\");\r\n                    $(row).children(\'td\').eq(10).attr(\"" +
"class\", \"td-manage\");\r\n                },\r\n                \"initComplete\": funct" +
"ion (settings, json) {\r\n\r\n                },\r\n                language: {\r\n     " +
"               lengthMenu: \'\',\r\n                    loadingRecords: \'数据加载中...\',\r" +
"\n                    paginate: {\r\n                        previous: \"上一页\",\r\n    " +
"                    next: \"下一页\",\r\n                        first: \"\",\r\n          " +
"              last: \"\"\r\n                    },\r\n                    zeroRecords:" +
" \"暂无数据\",\r\n\r\n                    info: \"<span class=\'pagesStyle\'>总共<span class=\'r" +
"ecordsStyle\'> _TOTAL_ 条,计 _PAGES_ </span>页，当前显示 _START_ -- _END_ 条记录 </span>\",\r\n" +
"                    infoEmpty: \"0条记录\",\r\n                    infoFiltered: \"\"\r\n  " +
"              },\r\n                \"searching\": false,\r\n                \"ordering" +
"\": false,\r\n                \"autoWidth\": false,\r\n                \"iDisplayLength\"" +
": 10,\r\n                \"processing\": true,\r\n                //destroy: true, //C" +
"annot reinitialise DataTable,解决重新加载表格内容问题\r\n\r\n            });\r\n            return" +
" dataTable;\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
