#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 7 "..\..\Views\Home\Certificate.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Home\Certificate.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Certificate.cshtml")]
    public partial class _Views_Home_Certificate_cshtml : System.Web.Mvc.WebViewPage<CertViewModel>
    {
        public _Views_Home_Certificate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Home\Certificate.cshtml"
  
    ViewBag.Title = "证书查询";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"query\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"position\"");

WriteLiteral(">当前位置：<a");

WriteAttribute("href", Tuple.Create(" href=\"", 161), Tuple.Create("\"", 196)
            
            #line 12 "..\..\Views\Home\Certificate.cshtml"
, Tuple.Create(Tuple.Create("", 168), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 168), false)
);

WriteLiteral(">首页</a> / <a");

WriteAttribute("href", Tuple.Create(" href=\"", 209), Tuple.Create("\"", 250)
            
            #line 12 "..\..\Views\Home\Certificate.cshtml"
         , Tuple.Create(Tuple.Create("", 216), Tuple.Create<System.Object, System.Int32>(Url.Action("Certificate", "Home")
            
            #line default
            #line hidden
, 216), false)
);

WriteLiteral(" class=\"red\"");

WriteLiteral(">证书查询</a></div>\r\n    <div");

WriteLiteral(" class=\"query_text\"");

WriteLiteral(">\r\n        <h5>");

            
            #line 14 "..\..\Views\Home\Certificate.cshtml"
        Write(Model.Title + "简介");

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n        <p>");

            
            #line 15 "..\..\Views\Home\Certificate.cshtml"
      Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"query_box\"");

WriteLiteral(">\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 438), Tuple.Create("\"", 503)
, Tuple.Create(Tuple.Create("", 446), Tuple.Create("query_div", 446), true)
            
            #line 18 "..\..\Views\Home\Certificate.cshtml"
, Tuple.Create(Tuple.Create(" ", 455), Tuple.Create<System.Object, System.Int32>(Model.CertType==CertType.teacher?"active":""
            
            #line default
            #line hidden
, 456), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 18 "..\..\Views\Home\Certificate.cshtml"
                                                                                     Write(CertType.teacher);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <p><i");

WriteLiteral(" class=\"iconfont icon-c_query\"");

WriteLiteral("></i>教师证书查询</p>\r\n            <select");

WriteLiteral(" class=\"select-city\"");

WriteLiteral(">\r\n                <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">选择市</option>\r\n");

            
            #line 22 "..\..\Views\Home\Certificate.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Home\Certificate.cshtml"
                 foreach (KeyValuePair<int, string> item in ViewBag.City)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 811), Tuple.Create("\"", 828)
            
            #line 24 "..\..\Views\Home\Certificate.cshtml"
, Tuple.Create(Tuple.Create("", 819), Tuple.Create<System.Object, System.Int32>(item.Key
            
            #line default
            #line hidden
, 819), false)
);

WriteLiteral(">");

            
            #line 24 "..\..\Views\Home\Certificate.cshtml"
                                         Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 25 "..\..\Views\Home\Certificate.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n            <input");

WriteLiteral(" class=\"input-number\"");

WriteLiteral(" placeholder=\"请输入教师姓或证书编号\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"search\"");

WriteLiteral("><i");

WriteLiteral(" class=\"iconfont icon-search\"");

WriteLiteral("></i></span>\r\n        </div><!--/query_div-->\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1108), Tuple.Create("\"", 1173)
, Tuple.Create(Tuple.Create("", 1116), Tuple.Create("query_div", 1116), true)
            
            #line 30 "..\..\Views\Home\Certificate.cshtml"
, Tuple.Create(Tuple.Create(" ", 1125), Tuple.Create<System.Object, System.Int32>(Model.CertType==CertType.student?"active":""
            
            #line default
            #line hidden
, 1126), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 30 "..\..\Views\Home\Certificate.cshtml"
                                                                                     Write(CertType.student);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <p><i");

WriteLiteral(" class=\"iconfont icon-c_query\"");

WriteLiteral("></i>学生证书查询</p>\r\n            <select");

WriteLiteral(" class=\"select-city\"");

WriteLiteral(">\r\n                <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">选择市</option>\r\n");

            
            #line 34 "..\..\Views\Home\Certificate.cshtml"
                
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Home\Certificate.cshtml"
                 foreach (KeyValuePair<int, string> item in ViewBag.City)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1481), Tuple.Create("\"", 1498)
            
            #line 36 "..\..\Views\Home\Certificate.cshtml"
, Tuple.Create(Tuple.Create("", 1489), Tuple.Create<System.Object, System.Int32>(item.Key
            
            #line default
            #line hidden
, 1489), false)
);

WriteLiteral(">");

            
            #line 36 "..\..\Views\Home\Certificate.cshtml"
                                         Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 37 "..\..\Views\Home\Certificate.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n            <input");

WriteLiteral(" class=\"input-number\"");

WriteLiteral(" placeholder=\"请输入学生姓或证书编号\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"search\"");

WriteLiteral("><i");

WriteLiteral(" class=\"iconfont icon-search\"");

WriteLiteral("></i></span>\r\n        </div><!--/query_div-->\r\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1769), Tuple.Create("\"", 1833)
, Tuple.Create(Tuple.Create("", 1777), Tuple.Create("query_div", 1777), true)
            
            #line 42 "..\..\Views\Home\Certificate.cshtml"
, Tuple.Create(Tuple.Create(" ", 1786), Tuple.Create<System.Object, System.Int32>(Model.CertType==CertType.member?"active":""
            
            #line default
            #line hidden
, 1787), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 42 "..\..\Views\Home\Certificate.cshtml"
                                                                                    Write(CertType.member);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <p><i");

WriteLiteral(" class=\"iconfont icon-c_query\"");

WriteLiteral("></i>会员单位查询</p>\r\n            <select");

WriteLiteral(" class=\"select-city\"");

WriteLiteral(">\r\n                <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">选择市</option>\r\n");

            
            #line 46 "..\..\Views\Home\Certificate.cshtml"
                
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Home\Certificate.cshtml"
                 foreach (KeyValuePair<int, string> item in ViewBag.City)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2140), Tuple.Create("\"", 2157)
            
            #line 48 "..\..\Views\Home\Certificate.cshtml"
, Tuple.Create(Tuple.Create("", 2148), Tuple.Create<System.Object, System.Int32>(item.Key
            
            #line default
            #line hidden
, 2148), false)
);

WriteLiteral(">");

            
            #line 48 "..\..\Views\Home\Certificate.cshtml"
                                         Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 49 "..\..\Views\Home\Certificate.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n            <input");

WriteLiteral(" class=\"input-number\"");

WriteLiteral(" placeholder=\"请输入会员名称或单位编号\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"search\"");

WriteLiteral("><i");

WriteLiteral(" class=\"iconfont icon-search\"");

WriteLiteral("></i></span>\r\n        </div><!--/query_div-->\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"query_cont\"");

WriteLiteral(" id=\"tbTable_wrapper\"");

WriteLiteral(">\r\n\r\n    </div><!--/query_cont-->\r\n");

            
            #line 59 "..\..\Views\Home\Certificate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Home\Certificate.cshtml"
     using (Ajax.BeginForm("CertificateList", new { }, new AjaxOptions { OnFailure = "showException", OnSuccess = "", UpdateTargetId = "tbTable_wrapper", OnBegin = "", OnComplete = "" }, new { id = "searchByRequest" }))
    {
        
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Home\Certificate.cshtml"
   Write(Html.Hidden("PageIndex", Model.PageFilter.PageIndex));

            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Home\Certificate.cshtml"
                                                             
        
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Home\Certificate.cshtml"
   Write(Html.Hidden("PageSize", Model.PageFilter.PageSize));

            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Home\Certificate.cshtml"
                                                           
        
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Home\Certificate.cshtml"
   Write(Html.Hidden("CityCode", Model.PageFilter.CityCode));

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Home\Certificate.cshtml"
                                                           
        
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Home\Certificate.cshtml"
   Write(Html.Hidden("NameOrNumber", Model.PageFilter.NameOrNumber));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Home\Certificate.cshtml"
                                                                   
        
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Home\Certificate.cshtml"
   Write(Html.Hidden("CertType", Model.CertType));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Home\Certificate.cshtml"
                                                
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            changeQueryCondition();\r\n" +
"\r\n            $(\".query_div\").on(\'click\', function () {\r\n                if ($(t" +
"his).hasClass(\"active\")) {\r\n                    return false;\r\n                }" +
" else {\r\n                    $(\"#CityCode,#NameOrNumber\").val(\"\");\r\n            " +
"        $(this).addClass(\"active\").siblings().removeClass(\"active\");\r\n          " +
"          $(\"#CertType\").val($(this).attr(\"data-bind\"));\r\n                    //" +
"请求数据\r\n                    changeQueryCondition();\r\n                }\r\n          " +
"  })\r\n\r\n            $(\".query_div .search\").on(\'click\', function (e) {\r\n        " +
"        e.stopPropagation();\r\n                $(this).parents(\".query_div\").addC" +
"lass(\"active\").siblings().removeClass(\"active\");\r\n                $(\"#CityCode\")" +
".val($(this).siblings(\"select.select-city\").val());\r\n                $(\"#NameOrN" +
"umber\").val($(this).siblings(\"input.input-number\").val());\r\n                $(\"#" +
"CertType\").val($(this).parents(\".query_div\").attr(\"data-bind\"));\r\n              " +
"  //请求数据\r\n                changeQueryCondition();\r\n\r\n                $(\'html, bo" +
"dy\').animate({\r\n                    scrollTop: $(\"#tbTable_wrapper\").offset().to" +
"p\r\n                }, 300);\r\n            })\r\n\r\n            $(\".select-city,.inpu" +
"t-number\").click(function (e) {\r\n                e.stopPropagation();\r\n         " +
"   })\r\n\r\n            $(\".query_div input.input-number\").keypress(function (e) {\r" +
"\n                if (e.which == 13) {\r\n                    $(this).focus();\r\n   " +
"                 $(this).siblings(\"span.search\").click();\r\n                }\r\n  " +
"          });\r\n        })\r\n\r\n        //改变筛选条件\r\n        function changeQueryCondi" +
"tion() {\r\n            $(\"#PageIndex\").val(1);//页索引置为1\r\n            $(\"#searchByR" +
"equest\").submit();\r\n        }\r\n\r\n        //改变索引页\r\n        function changePageInd" +
"ex(index) {\r\n            $(\"#PageIndex\").val(index);\r\n            $(\"#searchByRe" +
"quest\").submit();\r\n        }\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
