#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Home\Examination.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Home\Examination.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Examination.cshtml")]
    public partial class _Views_Home_Examination_cshtml : System.Web.Mvc.WebViewPage<WebContentViewModel>
    {
        public _Views_Home_Examination_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Examination.cshtml"
  
    ViewBag.Title = "考级中心";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"position\"");

WriteLiteral(">当前位置：<a");

WriteAttribute("href", Tuple.Create(" href=\"", 160), Tuple.Create("\"", 194)
            
            #line 9 "..\..\Views\Home\Examination.cshtml"
, Tuple.Create(Tuple.Create("", 167), Tuple.Create<System.Object, System.Int32>(Url.Action("index","home")
            
            #line default
            #line hidden
, 167), false)
);

WriteLiteral(">首页</a> / <a");

WriteAttribute("href", Tuple.Create(" href=\"", 207), Tuple.Create("\"", 240)
            
            #line 9 "..\..\Views\Home\Examination.cshtml"
        , Tuple.Create(Tuple.Create("", 214), Tuple.Create<System.Object, System.Int32>(Url.Action("examination")
            
            #line default
            #line hidden
, 214), false)
);

WriteLiteral(" class=\'red\'");

WriteLiteral(">考级中心</a></div>\r\n    <div");

WriteLiteral(" class=\"list_cont\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"list_fl fl\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"list_ul list_exam\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"title\"");

WriteLiteral(">考级中心</li>\r\n\r\n");

            
            #line 15 "..\..\Views\Home\Examination.cshtml"
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Home\Examination.cshtml"
                 if (ViewBag.Categorys != null)
                {
                    foreach (KeyValuePair<CategoryDictionary, List<CategoryDictionary>> item in ViewBag.Categorys)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteAttribute("class", Tuple.Create(" class=\"", 658), Tuple.Create("\"", 747)
            
            #line 19 "..\..\Views\Home\Examination.cshtml"
, Tuple.Create(Tuple.Create("", 666), Tuple.Create<System.Object, System.Int32>(Model.PageFilter!=null&&Model.PageFilter.ParCategory==item.Key.Id?"current":""
            
            #line default
            #line hidden
, 666), false)
);

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 781), Tuple.Create("\"", 863)
            
            #line 20 "..\..\Views\Home\Examination.cshtml"
, Tuple.Create(Tuple.Create("", 788), Tuple.Create<System.Object, System.Int32>(Url.Action("examination", new { qtype = QSType.list, pctype=item.Key.Id })
            
            #line default
            #line hidden
, 788), false)
);

WriteLiteral(">");

            
            #line 20 "..\..\Views\Home\Examination.cshtml"
                                                                                                             Write(item.Key.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 21 "..\..\Views\Home\Examination.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Home\Examination.cshtml"
                             foreach (CategoryDictionary citem in item.Value)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteAttribute("class", Tuple.Create(" class=\"", 1032), Tuple.Create("\"", 1115)
            
            #line 23 "..\..\Views\Home\Examination.cshtml"
, Tuple.Create(Tuple.Create("", 1040), Tuple.Create<System.Object, System.Int32>(Model.PageFilter!=null&&Model.PageFilter.Category==citem.Id?"current":""
            
            #line default
            #line hidden
, 1040), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1119), Tuple.Create("\"", 1218)
            
            #line 23 "..\..\Views\Home\Examination.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 1126), Tuple.Create<System.Object, System.Int32>(Url.Action("examination", new { qtype = QSType.list, fctype=citem.Id, pctype=item.Key.Id })
            
            #line default
            #line hidden
, 1126), false)
);

WriteLiteral(">");

            
            #line 23 "..\..\Views\Home\Examination.cshtml"
                                                                                                                                                                                                                            Write(citem.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></span>\r\n");

            
            #line 24 "..\..\Views\Home\Examination.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </li>\r\n");

            
            #line 26 "..\..\Views\Home\Examination.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n            </ul>\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Home\Examination.cshtml"
       Write(Html.Action("GetRecommend", new { sectionType = CategoryType.Examination }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 34 "..\..\Views\Home\Examination.cshtml"
        
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Home\Examination.cshtml"
         if (Model.QType != QSType.detail)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"list_fr fr\"");

WriteLiteral(" id=\"tbTable_wrapper\"");

WriteLiteral("></div>\r\n");

            
            #line 37 "..\..\Views\Home\Examination.cshtml"

        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Home\Examination.cshtml"
       Write(Html.Partial("GetDetail", Model.DetailModel));

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Home\Examination.cshtml"
                                                         
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 44 "..\..\Views\Home\Examination.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Home\Examination.cshtml"
         using (Ajax.BeginForm("GetArticList", new { }, new AjaxOptions { OnFailure = "showException", OnSuccess = "", UpdateTargetId = "tbTable_wrapper", OnBegin = "", OnComplete = "" }, new { id = "searchByRequest" }))
        {
            
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Home\Examination.cshtml"
       Write(Html.Hidden("PageIndex", Model.PageFilter.PageIndex));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Home\Examination.cshtml"
                                                                 
            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Home\Examination.cshtml"
       Write(Html.Hidden("PageSize", Model.PageFilter.PageSize));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Home\Examination.cshtml"
                                                               
            
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Home\Examination.cshtml"
       Write(Html.Hidden("Category", Model.PageFilter.Category));

            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Home\Examination.cshtml"
                                                               
            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Home\Examination.cshtml"
       Write(Html.Hidden("ParCategory", Model.PageFilter.ParCategory));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Home\Examination.cshtml"
                                                                     
            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Home\Examination.cshtml"
       Write(Html.Hidden("SectionType", Model.PageFilter.SectionType));

            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Home\Examination.cshtml"
                                                                     
        }

            
            #line default
            #line hidden
WriteLiteral("    </div><!--/list_cont-->\r\n</div><!--/list-->\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            if (\'");

            
            #line 58 "..\..\Views\Home\Examination.cshtml"
            Write(Model.QType);

            
            #line default
            #line hidden
WriteLiteral("\' != \'");

            
            #line 58 "..\..\Views\Home\Examination.cshtml"
                              Write(QSType.detail);

            
            #line default
            #line hidden
WriteLiteral(@"') {
                changeQueryCondition();
            }
        })

        //改变筛选条件
        function changeQueryCondition() {
            $(""#PageIndex"").val(1);//页索引置为1
            $(""#searchByRequest"").submit();
        }

        //改变索引页
        function changePageIndex(index) {
            $(""#PageIndex"").val(index);
            $(""#searchByRequest"").submit();
        }
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
