#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Home\Footer.cshtml"
    using HST.Art.Core;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Home\Footer.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Footer.cshtml")]
    public partial class _Views_Home_Footer_cshtml : System.Web.Mvc.WebViewPage<Organization>
    {
        public _Views_Home_Footer_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"foot_fl fl\"");

WriteLiteral(">\r\n    <p><span");

WriteLiteral(" style=\"margin-bottom:5px\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 133), Tuple.Create("\"", 152)
            
            #line 6 "..\..\Views\Home\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 139), Tuple.Create<System.Object, System.Int32>(Model.WeChat
            
            #line default
            #line hidden
, 139), false)
);

WriteLiteral(" onerror=\"nofind()\"");

WriteLiteral(" /></span>扫码关注我们</p>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"foot_conts fl\"");

WriteLiteral(">\r\n    <b>联系我们</b>\r\n    <p>");

            
            #line 11 "..\..\Views\Home\Footer.cshtml"
  Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 12 "..\..\Views\Home\Footer.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Home\Footer.cshtml"
     if (!string.IsNullOrEmpty(Model.Address))
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>地址：");

            
            #line 14 "..\..\Views\Home\Footer.cshtml"
          Write(Model.Address);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 15 "..\..\Views\Home\Footer.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 16 "..\..\Views\Home\Footer.cshtml"
     if (!string.IsNullOrEmpty(Model.Telephone))
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>电话：");

            
            #line 18 "..\..\Views\Home\Footer.cshtml"
          Write(Model.Telephone);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 19 "..\..\Views\Home\Footer.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 20 "..\..\Views\Home\Footer.cshtml"
     if (!string.IsNullOrEmpty(Model.Email))
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>邮箱：");

            
            #line 22 "..\..\Views\Home\Footer.cshtml"
          Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 23 "..\..\Views\Home\Footer.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("   \r\n</div>\r\n<p");

WriteLiteral(" class=\"fr index_ab\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 606), Tuple.Create("\"", 640)
            
            #line 26 "..\..\Views\Home\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 613), Tuple.Create<System.Object, System.Int32>(Url.Action("about","home")
            
            #line default
            #line hidden
, 613), false)
);

WriteLiteral("><i></i> 关于我们</a></p>\r\n");

        }
    }
}
#pragma warning restore 1591
