#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Home\MemberList.cshtml"
    using HST.Art.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/MemberList.cshtml")]
    public partial class _Views_Home_MemberList_cshtml : System.Web.Mvc.WebViewPage<PageListViewModel<MemberUnitViewModel>>
    {
        public _Views_Home_MemberList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Home\MemberList.cshtml"
 if (Model == null || Model.Count <= 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" class=\"not-data\"");

WriteLiteral(">暂无数据</p>\r\n");

            
            #line 7 "..\..\Views\Home\MemberList.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"dataTables_wrapper\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Home\MemberList.cshtml"
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Home\MemberList.cshtml"
         foreach (var item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"list_list\"");

WriteLiteral(">\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 281), Tuple.Create("\"", 372)
            
            #line 14 "..\..\Views\Home\MemberList.cshtml"
, Tuple.Create(Tuple.Create("", 288), Tuple.Create<System.Object, System.Int32>(Url.Action("About", new { qtype = QSType.detail, id=item.Id,fctype=item.Category })
            
            #line default
            #line hidden
, 288), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"list_img fl\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 417), Tuple.Create("\"", 441)
            
            #line 15 "..\..\Views\Home\MemberList.cshtml"
, Tuple.Create(Tuple.Create("", 423), Tuple.Create<System.Object, System.Int32>(item.SmallHeadImg
            
            #line default
            #line hidden
, 423), false)
);

WriteLiteral(" onerror=\"nofind()\"");

WriteLiteral(" /></div>\r\n            <div");

WriteLiteral(" class=\"list_cons fr\"");

WriteLiteral(">\r\n                <h6>");

            
            #line 17 "..\..\Views\Home\MemberList.cshtml"
               Write(item.MemberUnitName);

            
            #line default
            #line hidden
WriteLiteral("</h6>\r\n\r\n                <p>");

            
            #line 19 "..\..\Views\Home\MemberList.cshtml"
               Write(string.IsNullOrEmpty(item.Synopsis) ? item.MemberUnitName : item.Synopsis);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <span>");

            
            #line 20 "..\..\Views\Home\MemberList.cshtml"
                 Write(item.CreateTime);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n        </a>\r\n    </div>\r\n");

            
            #line 24 "..\..\Views\Home\MemberList.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"dataTables_info\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"pagesStyle\"");

WriteLiteral(">总共<span");

WriteLiteral(" class=\"recordsStyle\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Home\MemberList.cshtml"
                                                             Write(Model.TotalItemCount);

            
            #line default
            #line hidden
WriteLiteral(" 条,计 ");

            
            #line 27 "..\..\Views\Home\MemberList.cshtml"
                                                                                       Write(Model.TotalPageCount);

            
            #line default
            #line hidden
WriteLiteral(" </span>页，当前显示 ");

            
            #line 27 "..\..\Views\Home\MemberList.cshtml"
                                                                                                                           Write(Model.StartRecordIndex);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 27 "..\..\Views\Home\MemberList.cshtml"
                                                                                                                                                     Write(Model.EndRecordIndex);

            
            #line default
            #line hidden
WriteLiteral(" 条记录 </span>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"dataTables_paginate paging_simple_numbers\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Home\MemberList.cshtml"
       Write(Html.Page(Model.CurrentPageIndex, Model.TotalPageCount, "changePageIndex"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 33 "..\..\Views\Home\MemberList.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
